//! ISO 639-3 to ISO 639-1: the ONE owner of that conversion in batchalign3.
//!
//! # Why this is one owner
//!
//! Before this module, the conversion existed three times and agreed nowhere.
//! Python asked `pycountry` for it (`provider_lang_code`), and Rust had two
//! deliberately narrow per-engine tables that are NOT this conversion at all:
//! `whisper_native`'s maps to whisper.cpp's own tokens (`yue` stays `yue`,
//! which is not an ISO 639-1 code), and `revai_language`'s maps to Rev.AI's
//! accepted codes (`zho` and `cmn` both become `cmn`, likewise not ISO 639-1).
//! Those two remain, correctly, as PROVIDER code tables. What did not exist
//! was the standards fact underneath them, so a fourth caller that needed it
//! had to either invent a table or call into Python.
//!
//! An engine table may be derived from this one, but it may not be replaced by
//! it: a provider's accepted set is a fact about that provider.
//!
//! # Why it is partial, and why that is not an `Option`
//!
//! ISO 639-1 covers about 184 of ISO 639-3's ~7,900 languages. Having no
//! two-letter code is the NORMAL case and a fact about the standard, not a
//! missing row in this table: Mandarin (`cmn`) and Cantonese (`yue`) both have
//! none, while the macrolanguage `zho` has `zh`.
//!
//! The lookup therefore returns [`Iso639Part1Lookup`], a closed sum whose
//! absent arm is named [`Iso639Part1Lookup::NoTwoLetterCode`], rather than an
//! `Option` that invites `unwrap_or(three_letter_code)`. Substituting the
//! three-letter code is exactly the defect this replaces: it silently sent
//! providers codes like `16k_cmn` that no provider defines.
//!
//! # Where the data comes from
//!
//! [`table`] is generated by `scripts/generate_iso639_1_table.py` from
//! pycountry, whose database derives from the ISO 639-3 code tables published
//! by iso639-3.sil.org, the registration authority. Generating from the same
//! source the Python worker used means this conversion agrees with the
//! previous behaviour code for code. [`table::SOURCE`] carries the exact
//! provenance into the binary.

mod table;

pub use table::SOURCE;

/// A validated ISO 639-1 two-letter language code.
///
/// The field is private and the only constructor is the lookup below, so a
/// value of this type is proof that the registry pairs some ISO 639-3 code
/// with it. There is no route from an arbitrary string, which is what stops a
/// caller from inventing `"cmn"` or `"yue"` as though they were 639-1.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Iso639Part1(&'static str);

impl Iso639Part1 {
    /// The two-letter code.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        self.0
    }
}

impl std::fmt::Display for Iso639Part1 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.0)
    }
}

/// What the registry says about one ISO 639-3 code's two-letter form.
///
/// Closed and exhaustively matched by callers, so "this language has no ISO
/// 639-1 code" is a state a caller must handle rather than a `None` it can
/// paper over.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Iso639Part1Lookup {
    /// The registry pairs this language with a two-letter code.
    Paired(Iso639Part1),
    /// ISO 639-1 assigns this language no two-letter code. The normal case:
    /// only about 184 of ~7,900 ISO 639-3 languages have one.
    NoTwoLetterCode,
}

impl Iso639Part1Lookup {
    /// The paired code, or `None`.
    ///
    /// For a caller that genuinely has somewhere to put an absence, such as an
    /// `Option` field on a request. It deliberately does NOT offer a default:
    /// there is no correct substitute for a code the standard does not assign.
    #[must_use]
    pub const fn paired(self) -> Option<Iso639Part1> {
        match self {
            Self::Paired(code) => Some(code),
            Self::NoTwoLetterCode => None,
        }
    }
}

/// Look up the ISO 639-1 code for an ISO 639-3 code.
///
/// Binary search over the generated table, which the generator emits sorted by
/// the three-letter code. Callers normally reach this through
/// `LanguageCode3::to_iso_639_1`.
#[must_use]
pub fn lookup(alpha_3: &str) -> Iso639Part1Lookup {
    match table::ISO_639_3_TO_PART1.binary_search_by(|(code, _)| (*code).cmp(alpha_3)) {
        Ok(index) => Iso639Part1Lookup::Paired(Iso639Part1(table::ISO_639_3_TO_PART1[index].1)),
        Err(_) => Iso639Part1Lookup::NoTwoLetterCode,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generator emits the table sorted; the binary search is only correct
    /// if that holds, and a hand edit is exactly what would break it.
    #[test]
    fn the_generated_table_is_sorted_and_has_no_duplicates() {
        let codes: Vec<&str> = table::ISO_639_3_TO_PART1
            .iter()
            .map(|(alpha_3, _)| *alpha_3)
            .collect();
        let mut sorted = codes.clone();
        sorted.sort_unstable();
        assert_eq!(codes, sorted, "the generated table must be sorted");
        sorted.dedup();
        assert_eq!(
            sorted.len(),
            codes.len(),
            "a three-letter code must appear at most once"
        );
    }

    /// MEASUREMENT, with a range rather than an exact count: ISO 639-1 is a
    /// closed list that moves very rarely, and this is a floor against the
    /// table silently collapsing to nothing.
    #[test]
    fn the_table_is_about_the_size_iso_639_1_actually_is() {
        let count = table::ISO_639_3_TO_PART1.len();
        assert!(
            (150..250).contains(&count),
            "expected roughly 184 two-letter codes, got {count}"
        );
    }

    /// The pairs BA3 actually routes on, pinned by hand against the registry.
    #[test]
    fn well_known_languages_pair_as_the_registry_says() {
        for (alpha_3, expected) in [
            ("eng", "en"),
            ("spa", "es"),
            ("fra", "fr"),
            ("deu", "de"),
            ("jpn", "ja"),
            ("zho", "zh"),
            ("nld", "nl"),
            ("pol", "pl"),
        ] {
            assert_eq!(
                lookup(alpha_3),
                Iso639Part1Lookup::Paired(Iso639Part1(expected)),
                "{alpha_3} should pair with {expected}"
            );
        }
    }

    /// THE CASE THIS TYPE EXISTS FOR. Mandarin and Cantonese have no ISO 639-1
    /// code. The previous Python conversion fell back to the three-letter code
    /// here, which is how Tencent came to be asked for a `16k_cmn` model that
    /// does not exist.
    #[test]
    fn languages_with_no_two_letter_code_say_so_rather_than_substituting() {
        for alpha_3 in ["cmn", "yue", "wuu", "nan", "hak"] {
            assert_eq!(
                lookup(alpha_3),
                Iso639Part1Lookup::NoTwoLetterCode,
                "{alpha_3} has no ISO 639-1 code and must not be given one"
            );
        }
    }

    /// An unassigned or malformed code is absent, not a panic and not a guess.
    #[test]
    fn unknown_codes_are_absent() {
        for alpha_3 in ["zzz", "xyz", "", "en", "english"] {
            assert_eq!(lookup(alpha_3), Iso639Part1Lookup::NoTwoLetterCode);
        }
    }

    /// The absence arm carries no code, so `paired()` cannot hand one back.
    #[test]
    fn the_absent_arm_offers_no_code() {
        assert_eq!(lookup("cmn").paired(), None);
        assert_eq!(lookup("eng").paired().map(Iso639Part1::as_str), Some("en"));
    }

    /// Provenance travels with the binary.
    #[test]
    fn the_table_records_where_it_came_from() {
        assert!(SOURCE.contains("pycountry"), "{SOURCE}");
        assert!(SOURCE.contains("sil.org"), "{SOURCE}");
    }
}
