//! Output admission: writers accept a proof, never unchecked CHAT bytes.
//!
//! Every production output retains Chatter's complete admission, including
//! tier alignment. Transformed documents use checked typed construction;
//! unchanged documents carry the original bytes bound to their admitted parse.
//! Neither route reparses generated CHAT or fabricates parser provenance.
//!
//! Applied analysis also satisfies command-specific completion checks.
//! Comparison adds a census-based preservation check, not an exemption from
//! CHAT validity. Declined analysis may remove declared decision tiers, but
//! the resulting document must still pass complete construction admission.
//!
//! Model edits consume the previous proof and establish a new one before
//! serialization. Failed optional abbreviation merging retains the unmerged
//! admitted output. Unchanged output skips merging and provenance injection.
//! Serialization is cached only after admission, from the admitted model.
//!
//! A separately named, test-only double can stand in for an admitted worker
//! result; it cannot construct Chatter's production admission payload.
//!
//! # Output our own producer generated
//!
//! Every route above refuses: a command that transforms CHAT someone
//! submitted fails the file rather than write a document Chatter does not
//! admit. Transcription is different in kind. Its CHAT is generated by our own
//! code from an ASR response, so an admission failure there is a fact about
//! the generated document (an ASR token such as `b2` or `Www` kept verbatim
//! for human review, or a defect in our builder), never bad user input, and
//! the generated document is the most valuable evidence anyone has of it.
//! [`PostValidated::produced`] is the one transition for that case. It runs
//! exactly the same judgement as [`PostValidated::gate_owned`] and never
//! fails: it returns a [`ProducedOutput`], which is either an admitted
//! [`PostValidated`] or a [`DiagnosedOutput`] carrying the model and the
//! complete, non-empty list of what the judgement found. Validation is not
//! relaxed; what changes is that the verdict travels beside the bytes instead
//! of replacing them.
//!
//! A [`PostValidated`] therefore proves admission, always: the diagnosed case
//! is a different type, so no stage that requires an admitted document can be
//! handed one, and no method needs an arm for it.
//!
//! ```mermaid
//! stateDiagram-v2
//!     [*] --> Judged: produced(model, command)
//!     Judged --> Admitted: judgement passes (PostValidated)
//!     Judged --> Diagnosed: judgement finds anything (DiagnosedOutput)
//!     Admitted --> Admitted: later stage (utseg, morphosyntax)
//!     Admitted --> Admitted: later stage refused, pre-stage kept, shortfall recorded
//!     Diagnosed --> Diagnosed: later stage skipped, shortfall recorded
//!     Admitted --> Written: writer, file Done (or Diagnosed with shortfalls)
//!     Diagnosed --> Written: writer, file Diagnosed with findings
//! ```
//!
//! # Requested work the written output does not carry
//!
//! A [`Shortfall`] is requested work the written document does not include,
//! and why: a later stage skipped because the generated document was
//! diagnosed, or an optional stage whose own output could not be admitted, so
//! the admitted document from before it was kept. Shortfalls are facts about
//! the run, not about the document, so they are carried beside the proof by
//! the producer that knows them and reported by the writer whatever the
//! document's standing ([`OutputReport::of`]). A file with any shortfall is
//! never reported clean.

use std::sync::OnceLock;

use crate::api::ReleasedCommand;
use batchalign_transform::merge_abbreviations;
use batchalign_transform::serialize::to_chat_string;
use batchalign_transform::validate::{ValidationError, ValidityLevel, validate_output};
use talkbank_model::ChatFile;
use talkbank_model::model::Line;
use talkbank_model::model::TranscriptName;
use talkbank_model::validation::{
    AlignmentValidation, ValidChatFile, ValidationFailure, ValidationPolicy,
};

/// Production output retains Chatter's immutable construction admission.
/// Test doubles are a separate, test-only state and cannot forge that proof.
#[derive(Debug, Clone)]
enum OutputDocument {
    Checked(ValidChatFile),
    #[cfg(test)]
    Double(ChatFile),
}

impl OutputDocument {
    fn document(&self) -> &ChatFile {
        match self {
            Self::Checked(file) => file.document(),
            #[cfg(test)]
            Self::Double(file) => file,
        }
    }

    fn into_unchecked(self) -> ChatFile {
        match self {
            Self::Checked(file) => file.into_unchecked(),
            #[cfg(test)]
            Self::Double(file) => file,
        }
    }
}

/// A command's output that has passed the post-validation gate, together with
/// the document that passed it.
///
/// Possession of one of these IS the proof. Transformed bytes derive from its
/// checked model; unchanged bytes remain bound to their admitted source parse.
/// A caller cannot validate one model and write another. It always proves
/// admission: a generating producer's output that the judgement refused is a
/// [`DiagnosedOutput`], a different type ([`Self::produced`]).
///
/// `Clone` and `PartialEq` are written out rather than derived because
/// [`OutputProof::Gated`] carries a materialization cache, and a cache is not
/// part of the document's identity. See the impls below.
#[derive(Debug)]
pub(crate) struct PostValidated {
    /// The command whose output this document is.
    ///
    /// Held here rather than inside [`OutputProof::Gated`] because it is true
    /// of every route: an unchanged document is still SOME command's output,
    /// and the writer needs the name whichever route produced the bytes.
    command: ReleasedCommand,
    /// What makes this document admissible, and at what bar.
    proof: OutputProof,
}

/// Evidence that authorizes this command's output.
#[derive(Debug)]
enum OutputProof {
    /// Checked construction plus the recorded command/preservation checks.
    Gated {
        judgement: Judgement,
        file: Box<OutputDocument>,
        /// Derived lazily from the checked model, at most once per proof.
        text: OnceLock<String>,
    },
    /// Declined analysis, with declared tier removal and checked construction.
    /// No analysis-completion claim or later cosmetic edit is permitted.
    Declined {
        file: Box<OutputDocument>,
        text: String,
    },
    /// Strictly admitted original bytes and their immutable, bound model.
    PassedThrough {
        // Keep every output an inexpensive ownership handle. An inline source
        // model inflates all async frames, even on transformed-output paths.
        source: Box<batchalign_transform::AdmittedSourceChat<'static>>,
    },
}

/// Output our own producer generated that the judgement did not admit, with
/// every finding. Built only by [`PostValidated::produced`]; written with its
/// diagnostics, and never handed to a stage that needs an admitted document,
/// because those take a [`PostValidated`].
#[derive(Debug)]
pub(crate) struct DiagnosedOutput {
    /// The command whose output this document is.
    command: ReleasedCommand,
    /// Boxed so the sum it lives in stays an inexpensive ownership handle.
    document: Box<DiagnosedDocument>,
}

/// The parts of a diagnosed output: the model the judgement ran over, its
/// lazily derived bytes, and what the judgement found.
#[derive(Debug)]
struct DiagnosedDocument {
    /// The model as generated. Not admitted, so it is never `ValidChatFile`.
    file: ChatFile,
    /// Derived lazily from `file`, at most once, like `Gated::text`.
    text: OnceLock<String>,
    /// Every finding, never empty.
    findings: OutputFindings,
}

impl Clone for DiagnosedOutput {
    fn clone(&self) -> Self {
        Self {
            command: self.command,
            document: Box::new(DiagnosedDocument {
                file: self.document.file.clone(),
                text: clone_materialized(&self.document.text),
                findings: self.document.findings.clone(),
            }),
        }
    }
}

impl PartialEq for DiagnosedOutput {
    /// The model, as for [`PostValidated`]: the findings are derived from it
    /// by the one judgement, so equal models carry equal findings.
    fn eq(&self, other: &Self) -> bool {
        self.command == other.command && self.document.file == other.document.file
    }
}

impl DiagnosedOutput {
    /// The command whose output this is.
    pub(crate) fn command(&self) -> ReleasedCommand {
        self.command
    }

    /// What the judgement found: never empty.
    pub(crate) fn findings(&self) -> &OutputFindings {
        &self.document.findings
    }

    /// The generated bytes, serialized at most once.
    pub(crate) fn as_str(&self) -> &str {
        self.document
            .text
            .get_or_init(|| to_chat_string(&self.document.file))
    }

    /// Take ownership of the generated bytes.
    pub(crate) fn into_text(self) -> String {
        let DiagnosedDocument { file, text, .. } = *self.document;
        match text.into_inner() {
            Some(materialized) => materialized,
            None => to_chat_string(&file),
        }
    }

    /// Merge abbreviations on the model and judge it afresh by the producer
    /// transition: it may now pass, or carry different findings. Never
    /// refused, because a diagnosed output is written whatever the judgement
    /// says.
    fn with_abbreviations_merged(self) -> ProducedOutput {
        let command = self.command;
        let DiagnosedDocument { mut file, .. } = *self.document;
        merge_abbreviations(&mut file);
        PostValidated::produced(file, command)
    }

    /// The refusal this diagnosis amounts to, for a consumer whose own
    /// deliverable needs an admitted document and cannot be produced without
    /// one (benchmark compares the transcript; a diagnosed transcript has
    /// nothing admitted to compare).
    pub(crate) fn into_failure(self) -> PostValidationFailure {
        PostValidationFailure {
            command: self.command,
            findings: self.document.findings,
        }
    }
}

/// A diagnosed output whose findings belong to identified utterances: with
/// those utterances held out, the rest of the document is admitted.
///
/// This is what lets a later per-utterance stage (utterance segmentation,
/// morphosyntax) refuse only the faulty utterances instead of the whole file. Built only by
/// [`DiagnosedOutput::localize`], which established both facts by judgement:
/// each held-out utterance fails on its own, and the document without them
/// passes. A stage that consumes it edits only the other utterances and must
/// judge its result afresh ([`PostValidated::produced`]); holding this value
/// grants no admission.
#[derive(Debug, Clone)]
pub(crate) struct LocalizedDiagnosis {
    diagnosed: DiagnosedOutput,
    held_out: HeldOutUtterances,
}

/// The utterances a diagnosed document's findings are confined to, by
/// ordinal among the file's utterances: ascending and never empty, which
/// [`DiagnosedOutput::localize`], the only constructor, establishes. A stage
/// asks [`Self::contains`] rather than searching a bare list whose order
/// nothing enforced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct HeldOutUtterances(Vec<usize>);

/// Where applying a stage's results left the file's utterances, so a
/// judgement of the result can find the utterances the stage was not given.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum AppliedLayout {
    /// Every utterance is where it was: the stage edits utterances in place.
    InPlace,
    /// The stage split utterances; where each input utterance went, as the
    /// split that performed it recorded.
    Segmented(batchalign_transform::utseg::SegmentationLayout),
}

/// The held-out utterances at their positions in a stage's OUTPUT, which
/// [`PostValidated::produced_outside`] judges.
///
/// A different type from [`HeldOutUtterances`], which holds positions in the
/// stage's INPUT: segmentation renumbers utterances, so the two are different
/// index spaces, and only [`HeldOutUtterances::in_place`] and
/// [`HeldOutUtterances::after`] cross from one to the other.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct HeldOutInOutput(Vec<usize>);

impl HeldOutInOutput {
    /// Whether the output utterance at this ordinal is held out.
    fn contains(&self, ordinal: usize) -> bool {
        self.0.binary_search(&ordinal).is_ok()
    }
}

impl HeldOutUtterances {
    /// The same utterances in the output of a stage that edits utterances in
    /// place (morphosyntax): the positions do not change.
    pub(crate) fn in_place(&self) -> HeldOutInOutput {
        HeldOutInOutput(self.0.clone())
    }

    /// The same utterances, at their positions in a stage's output.
    ///
    /// A held-out utterance is never collected for the stage, so it is never
    /// given an assignment: it stays one utterance and only moves down past
    /// the extra children of splits before it. `None` when the layout records
    /// a split of one (or has no such utterance), which only a stage that
    /// applied a result to an utterance it was not given can cause; its output
    /// cannot then be judged against them. The layout records splits only;
    /// that a held-out utterance is otherwise untouched rests on its never
    /// being collected.
    pub(crate) fn after(&self, layout: &AppliedLayout) -> Option<HeldOutInOutput> {
        match layout {
            AppliedLayout::InPlace => Some(self.in_place()),
            // Ascending stays ascending: a whole utterance's output position
            // grows with its input position.
            AppliedLayout::Segmented(layout) => self
                .0
                .iter()
                .map(|&ordinal| layout.whole_output_ordinal(ordinal))
                .collect::<Option<Vec<usize>>>()
                .map(HeldOutInOutput),
        }
    }

    /// Whether the utterance at this ordinal is held out.
    pub(crate) fn contains(&self, ordinal: usize) -> bool {
        self.0.binary_search(&ordinal).is_ok()
    }

    /// How many utterances are held out, at least one.
    pub(crate) fn len(&self) -> usize {
        self.0.len()
    }

    /// The held-out ordinals, ascending.
    pub(crate) fn ordinals(&self) -> impl Iterator<Item = usize> + '_ {
        self.0.iter().copied()
    }
}

impl DiagnosedOutput {
    /// Find the utterances that carry this output's findings, or give the
    /// output back when they cannot be confined to utterances.
    ///
    /// Each utterance is judged on its own, in a document holding only the
    /// headers and that utterance; one that fails is held out. The document
    /// without the held-out utterances is then judged: only if it passes are
    /// the findings confined to them. A finding about the document as a
    /// whole (a header, or a relation between utterances) leaves nothing to
    /// hold out or does not go away, and the output comes back unchanged. An
    /// utterance that fails only in isolation is held out too, which costs
    /// it only the stage, never its content.
    pub(crate) fn localize(mut self) -> Result<LocalizedDiagnosis, Self> {
        // The lines are moved out for the duration, so the document's other
        // parts (headers' derived facts) are cloned without any line, and
        // every judged document is built from exactly the lines it holds:
        // nothing is cloned to be thrown away.
        let lines = std::mem::replace(
            &mut self.document.file.lines,
            talkbank_model::model::ChatFileLines::new(Vec::new()),
        );
        let with_lines = |kept: Vec<Line>| {
            let mut document = self.document.file.clone();
            document.lines = talkbank_model::model::ChatFileLines::new(kept);
            document
        };
        let is_utterance = |line: &Line| matches!(line, Line::Utterance(_));
        let headers: Vec<&Line> = lines.iter().filter(|line| !is_utterance(line)).collect();
        // Where the utterances sit among the headers: after every header
        // that precedes the first utterance.
        let position = lines.iter().take_while(|line| !is_utterance(line)).count();
        let held_out: Vec<usize> = lines
            .iter()
            .filter(|line| is_utterance(line))
            .enumerate()
            .filter(|(_, utterance)| {
                let mut alone: Vec<Line> = headers.iter().map(|line| (*line).clone()).collect();
                alone.insert(position, (*utterance).clone());
                matches!(
                    PostValidated::assess(with_lines(alone), &Judgement::Admitted, self.command),
                    Assessment::Refused { .. }
                )
            })
            .map(|(ordinal, _)| ordinal)
            .collect();
        // Ascending by construction: ordinals enumerated in order.
        let localized = !held_out.is_empty() && {
            let mut ordinal = 0;
            let remainder: Vec<Line> = lines
                .iter()
                .filter(|line| match line {
                    Line::Utterance(_) => {
                        let keep = held_out.binary_search(&ordinal).is_err();
                        ordinal += 1;
                        keep
                    }
                    _ => true,
                })
                .cloned()
                .collect();
            matches!(
                PostValidated::assess(with_lines(remainder), &Judgement::Admitted, self.command),
                Assessment::Admitted(_)
            )
        };
        self.document.file.lines = lines;
        if localized {
            Ok(LocalizedDiagnosis {
                diagnosed: self,
                held_out: HeldOutUtterances(held_out),
            })
        } else {
            Err(self)
        }
    }
}

impl LocalizedDiagnosis {
    /// The held-out utterances.
    pub(crate) fn held_out(&self) -> &HeldOutUtterances {
        &self.held_out
    }

    /// The diagnosed bytes, as they stand before the stage.
    pub(crate) fn as_str(&self) -> &str {
        self.diagnosed.as_str()
    }

    /// The diagnosed model, to read before deciding whether a stage runs.
    pub(crate) fn model(&self) -> &ChatFile {
        &self.diagnosed.document.file
    }

    /// The diagnosed output unchanged, for a stage that declines to run.
    pub(crate) fn into_diagnosed(self) -> DiagnosedOutput {
        self.diagnosed
    }

    /// The model, to edit outside the held-out utterances, with them. The
    /// edited model has no standing until it is judged again.
    pub(crate) fn into_model(self) -> (ChatFile, HeldOutUtterances) {
        let DiagnosedDocument { file, .. } = *self.diagnosed.document;
        (file, self.held_out)
    }
}

/// What a generating producer's judgement concluded: an admitted proof, or a
/// diagnosed document with its findings. The writer takes this sum, so it
/// needs no runtime check to tell the two apart.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum ProducedOutput {
    /// The output passed its judgement.
    Admitted(PostValidated),
    /// The output did not pass; it is written with its findings.
    Diagnosed(DiagnosedOutput),
}

impl From<PostValidated> for ProducedOutput {
    /// Total: an admitted proof is admitted output.
    fn from(admitted: PostValidated) -> Self {
        Self::Admitted(admitted)
    }
}

impl ProducedOutput {
    /// The command whose output this is.
    pub(crate) fn command(&self) -> ReleasedCommand {
        match self {
            Self::Admitted(admitted) => admitted.command(),
            Self::Diagnosed(diagnosed) => diagnosed.command(),
        }
    }

    /// The bytes to write, serialized at most once.
    pub(crate) fn as_str(&self) -> &str {
        match self {
            Self::Admitted(admitted) => admitted.as_str(),
            Self::Diagnosed(diagnosed) => diagnosed.as_str(),
        }
    }

    /// Take ownership of the bytes to write.
    pub(crate) fn into_text(self) -> String {
        match self {
            Self::Admitted(admitted) => admitted.into_text(),
            Self::Diagnosed(diagnosed) => diagnosed.into_text(),
        }
    }

    /// [`PostValidated::with_abbreviations_merged`] for an admitted output; a
    /// diagnosed one is merged and judged afresh by the producer transition.
    pub(crate) fn with_abbreviations_merged(self) -> Result<Self, Box<AbbreviationMergeRefused>> {
        match self {
            Self::Admitted(admitted) => admitted.with_abbreviations_merged().map(Self::Admitted),
            Self::Diagnosed(diagnosed) => Ok(diagnosed.with_abbreviations_merged()),
        }
    }
}

/// What a CHAT writer may persist: the bytes of a judged proof, and the
/// command whose output they are. Implemented only by the two proof types, so
/// a writer cannot be handed a bare string.
pub(crate) trait WritableChat {
    /// The bytes to write.
    fn chat_text(&self) -> &str;
    /// The command whose output they are.
    fn chat_command(&self) -> ReleasedCommand;
}

impl WritableChat for PostValidated {
    fn chat_text(&self) -> &str {
        self.as_str()
    }
    fn chat_command(&self) -> ReleasedCommand {
        self.command()
    }
}

impl WritableChat for ProducedOutput {
    fn chat_text(&self) -> &str {
        self.as_str()
    }
    fn chat_command(&self) -> ReleasedCommand {
        self.command()
    }
}

/// An optional later stage of a generating producer: the wire enum is the
/// one owner of the closed set.
pub(crate) use crate::api::OptionalStage;

/// Requested work a written output does not carry, and why. A fact about the
/// run, carried beside the document by the producer that knows it and
/// reported whatever the document's standing: a file with any shortfall is
/// reported diagnosed, never clean. The wire record is the one owner.
pub(crate) type Shortfall = crate::api::OutputShortfallRecord;

/// Part of the input a producer left out of its work on purpose, by a
/// recorded ruling. Reported beside the written output on a separate channel
/// from [`Shortfall`]: it is information, and never makes a file diagnosed,
/// so [`OutputReport::of`] does not take it. The wire record is the one
/// owner.
pub(crate) type Exclusion = crate::api::OutputExclusionRecord;

/// How a written output is reported: clean, or with diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum OutputReport {
    /// Admitted, and nothing requested is missing.
    Clean,
    /// Written with these diagnostics: the judgement's findings, the
    /// shortfalls, or both. Never empty. A draft until it is recorded.
    Diagnosed(DiagnosticsDraft),
}

impl OutputReport {
    /// The one owner of "is this file clean": an admitted document with no
    /// shortfall. Exhaustive over both facts, so neither can be forgotten.
    pub(crate) fn of(output: &ProducedOutput, shortfalls: &[Shortfall]) -> Self {
        let findings = match output {
            ProducedOutput::Admitted(_) => None,
            ProducedOutput::Diagnosed(diagnosed) => Some(diagnosed.findings()),
        };
        match (findings, shortfalls) {
            (None, []) => Self::Clean,
            (findings, shortfalls) => Self::Diagnosed(DiagnosticsDraft {
                findings: findings.cloned(),
                shortfalls: shortfalls.to_vec(),
            }),
        }
    }
}

/// A diagnosed file's complete diagnostics, before they are recorded.
///
/// Recording bounds them: the record keeps the count, a count per code and
/// the first findings, and a longer list is written once, in full, to a
/// sidecar file. A draft cannot reach the store; only [`Self::record`]
/// produces the record it keeps.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DiagnosticsDraft {
    /// What the judgement found, with its bar; absent when the document was
    /// admitted and only shortfalls diagnose it. Never absent together with
    /// an empty `shortfalls`: [`OutputReport::of`] is the only constructor,
    /// and that case is [`OutputReport::Clean`].
    findings: Option<OutputFindings>,
    shortfalls: Vec<Shortfall>,
}

impl DiagnosticsDraft {
    /// Every finding, in the order the judgement found them; none when the
    /// document was admitted.
    pub(crate) fn findings(&self) -> impl Iterator<Item = &Finding> {
        self.findings.iter().flat_map(OutputFindings::errors)
    }

    /// Every shortfall, in the order it was recorded.
    pub(crate) fn shortfalls(&self) -> &[Shortfall] {
        &self.shortfalls
    }

    /// Record the diagnostics, writing the complete list of findings to
    /// `sidecar` (as JSON) only when it does not fit on the record.
    ///
    /// Never fails: it runs after the output is on disk, and a diagnostics
    /// file that cannot be written does not unmake a written output. A failed
    /// write is recorded as [`crate::api::FullFindings::Unwritten`]. A list
    /// that fits removes any sidecar an earlier attempt left at that path, so
    /// no stale list sits beside a record that does not name it.
    pub(crate) async fn record(
        self,
        sidecar: &std::path::Path,
    ) -> crate::api::FileOutputDiagnostics {
        let Self {
            findings,
            shortfalls,
        } = self;
        let Some(findings) = findings else {
            // Admitted, diagnosed only for its shortfalls: no list to record.
            remove_stale_sidecar(sidecar).await;
            return crate::api::FileOutputDiagnostics {
                findings: None,
                shortfalls,
            };
        };
        let (bar, findings) = findings.into_bar_and_list();
        let path = || sidecar.to_string_lossy().into_owned();
        let full_findings = if findings.len() > crate::api::FileOutputDiagnostics::FIRST_FINDINGS {
            match write_sidecar(sidecar, &findings).await {
                Ok(()) => crate::api::FullFindings::Sidecar { path: path() },
                Err(error) => {
                    tracing::warn!(sidecar = %sidecar.display(), %error, "could not write the full findings list");
                    crate::api::FullFindings::Unwritten {
                        path: path(),
                        error: error.to_string(),
                    }
                }
            }
        } else {
            remove_stale_sidecar(sidecar).await;
            crate::api::FullFindings::Inline
        };
        crate::api::FileOutputDiagnostics {
            findings: Some(crate::api::JudgedFindingsRecord {
                bar,
                finding_count: findings.len() as u64,
                findings_by_code: crate::api::FindingCodeCount::tally(&findings),
                first_findings: findings
                    .into_iter()
                    .take(crate::api::FileOutputDiagnostics::FIRST_FINDINGS)
                    .collect(),
                full_findings,
            }),
            shortfalls,
        }
    }
}

/// Remove any sidecar an earlier attempt of the file left at this path, so no
/// stale list sits beside a record that does not name it.
async fn remove_stale_sidecar(sidecar: &std::path::Path) {
    match tokio::fs::remove_file(sidecar).await {
        Ok(()) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            tracing::warn!(sidecar = %sidecar.display(), %error, "could not remove an earlier attempt's findings list");
        }
    }
}

/// Write the complete findings list as JSON, creating its directory.
async fn write_sidecar(sidecar: &std::path::Path, findings: &[Finding]) -> std::io::Result<()> {
    if let Some(parent) = sidecar.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    let json = serde_json::to_vec_pretty(findings).map_err(std::io::Error::other)?;
    tokio::fs::write(sidecar, json).await
}

/// Copy a materialization cache: a clone of an already serialized proof does
/// not serialize again.
fn clone_materialized(text: &OnceLock<String>) -> OnceLock<String> {
    let cell = OnceLock::new();
    if let Some(materialized) = text.get() {
        // Infallible on a cell made one line above; the `Result` is dropped
        // rather than unwrapped because this module does not panic.
        let _ = cell.set(materialized.clone());
    }
    cell
}

/// Every finding one judgement made, never empty.
///
/// Non-emptiness is the type's, not a convention: the first finding is a
/// field of its own, and the two constructors either find one in a list or
/// are handed the statement to use when a refusal named none.
#[derive(Debug, Clone, PartialEq, Eq)]
struct Findings {
    first: Finding,
    rest: Vec<Finding>,
}

/// One finding, typed: its CHAT error code when it has one, its validity
/// level and its message. The wire record is the one owner of the shape.
pub(crate) type Finding = crate::api::OutputFindingRecord;

/// A gate's coarse finding (a command's completion or preservation check),
/// which names no code.
fn gate_finding(error: ValidationError) -> Finding {
    let ValidationError { message, level } = error;
    Finding {
        code: None,
        level: finding_level(level),
        message,
    }
}

/// The wire level of a validity level. Exhaustive, so a new level must say
/// how it is reported.
fn finding_level(level: ValidityLevel) -> crate::api::FindingLevel {
    match level {
        ValidityLevel::Parseable => crate::api::FindingLevel::Parseable,
        ValidityLevel::StructurallyComplete => crate::api::FindingLevel::StructurallyComplete,
        ValidityLevel::MainTierValid => crate::api::FindingLevel::MainTierValid,
    }
}

impl Findings {
    /// The findings in `errors`, or `None` when there are none (the judgement
    /// passed).
    fn of(errors: Vec<Finding>) -> Option<Self> {
        let mut errors = errors.into_iter();
        let first = errors.next()?;
        Some(Self {
            first,
            rest: errors.collect(),
        })
    }

    /// The findings in `errors`, or `statement` when a refusal reported none:
    /// a typed admission verdict can refuse without any error diagnostic.
    fn or_statement(errors: Vec<Finding>, statement: Finding) -> Self {
        let mut errors = errors.into_iter();
        match errors.next() {
            Some(first) => Self {
                first,
                rest: errors.collect(),
            },
            None => Self {
                first: statement,
                rest: Vec::new(),
            },
        }
    }

    fn iter(&self) -> impl Iterator<Item = &Finding> {
        std::iter::once(&self.first).chain(&self.rest)
    }
}

/// What a judgement found in one output: the bar it was held to and every
/// finding, never empty.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct OutputFindings {
    bar: JudgementBar,
    findings: Findings,
}

impl OutputFindings {
    /// What complete construction admission's refusal found, after the
    /// `prior` findings of earlier checks: each of its diagnostics, or its
    /// own statement when it named none. Recovery or producer failure can
    /// refuse with no error diagnostic present; the typed admission verdict
    /// owns the refusal, not the length of a diagnostic collection.
    fn of_construction_refusal(
        bar: JudgementBar,
        mut prior: Vec<Finding>,
        failure: &ValidationFailure,
    ) -> Self {
        prior.extend(failure.diagnostics().iter().map(|diagnostic| Finding {
            code: Some(diagnostic.code.as_str().to_owned()),
            level: crate::api::FindingLevel::Construction,
            message: diagnostic.message.clone(),
        }));
        let statement = Finding {
            code: None,
            level: crate::api::FindingLevel::Construction,
            message: failure.to_string(),
        };
        Self {
            bar,
            findings: Findings::or_statement(prior, statement),
        }
    }

    /// The bar the output was judged against.
    pub(crate) fn bar(&self) -> JudgementBar {
        self.bar
    }

    /// Every finding, in the order the judgement found them. Never empty.
    pub(crate) fn errors(&self) -> impl Iterator<Item = &Finding> {
        self.findings.iter()
    }

    /// The first finding: there always is one.
    pub(crate) fn first(&self) -> &Finding {
        &self.findings.first
    }

    /// How many findings there are, at least one.
    pub(crate) fn count(&self) -> usize {
        1 + self.findings.rest.len()
    }

    /// The bar and every finding as one list, for recording.
    fn into_bar_and_list(self) -> (JudgementBar, Vec<Finding>) {
        let Findings { first, rest } = self.findings;
        (self.bar, std::iter::once(first).chain(rest).collect())
    }

    fn render(&self) -> String {
        self.errors()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("; ")
    }
}

/// Additional checks beyond complete Chatter construction admission.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Judgement {
    /// Applied analysis must satisfy the command's completion checks.
    Admitted,
    /// Declined analysis performs only its declared tier removal.
    Declined,
    /// Comparison must also retain the input's utterance structure.
    Preserved(UtteranceCensus),
}

impl Judgement {
    /// The bar a refusal reports.
    ///
    /// A projection rather than a second copy: a failure message needs to say
    /// which claim failed and has no business carrying the census it was
    /// measured against, and deriving it here means a new judgement must state
    /// how it renders.
    fn bar(&self) -> JudgementBar {
        match self {
            Self::Admitted | Self::Declined => JudgementBar::Construction,
            Self::Preserved(_) => JudgementBar::Preservation,
        }
    }
}

/// The bar an output was judged against: the wire type is the one owner.
pub(crate) use crate::api::JudgementBar;

/// What a document's utterances WERE, before a command touched them.
///
/// # Why it exists
///
/// It is the input half of a preservation judgement. Compare and benchmark
/// must retain the utterances and terminators their input had, in addition
/// to establishing complete checked construction for their output. A census
/// never exempts malformed output from admission.
///
/// # Every route to one
///
/// [`UtteranceCensus::of`] and nothing else: the fields are private and no
/// other constructor exists, so a caller cannot state what an input had
/// without holding that input. That matters in both directions, because a
/// census determines which preservation losses can be detected. Its private
/// fields prevent a caller from hiding those losses behind an empty census.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct UtteranceCensus {
    /// One entry per main tier, in document order.
    utterances: Vec<CensusEntry>,
}

/// One utterance, in as much detail as preservation is about.
#[derive(Debug, Clone, PartialEq, Eq)]
struct CensusEntry {
    /// The speaker code. Carried so the positional correspondence between the
    /// two documents is CHECKED rather than assumed; see
    /// [`UtteranceCensus::losses_in`].
    speaker: String,
    /// Whether this utterance carried a terminator.
    has_terminator: bool,
}

impl UtteranceCensus {
    /// Take the census of a document.
    pub(crate) fn of(file: &ChatFile) -> Self {
        Self {
            utterances: file
                .lines
                .iter()
                .filter_map(|line| match line {
                    Line::Utterance(utt) => Some(CensusEntry {
                        speaker: utt.main.speaker.as_str().to_owned(),
                        has_terminator: utt.main.content.terminator.is_some(),
                    }),
                    // Headers and free-standing tiers are not what preservation
                    // is about here, and a command that adds one (compare's
                    // `@Media` line) must not read as a changed document.
                    _ => None,
                })
                .collect(),
        }
    }

    /// Everything `output` LOST relative to this census.
    ///
    /// The comparison is positional, and the speaker check is what makes that
    /// legitimate rather than assumed: the commands judged this way edit
    /// headers and dependent tiers, so utterance N of the output is utterance
    /// N of the input, and on the day that stops being true the mismatch is
    /// REPORTED instead of two unrelated utterances being silently compared.
    /// An output with MORE utterances than its input has lost nothing by that
    /// alone, so only a shortfall is a finding.
    fn losses_in(&self, output: &ChatFile, command: ReleasedCommand) -> Vec<ValidationError> {
        let mut errors = Vec::new();
        // Walked lazily rather than censused: a second census would allocate a
        // speaker `String` per utterance of a document this only ever reads.
        let mut after = output.lines.iter().filter_map(|line| match line {
            Line::Utterance(utt) => Some(utt),
            _ => None,
        });
        let mut kept = 0usize;

        for before in &self.utterances {
            let Some(now) = after.next() else {
                // The output ran out, so `kept` is its whole length and every
                // remaining input utterance is missing from it.
                break;
            };
            kept += 1;

            let speaker = now.main.speaker.as_str();
            if before.speaker != speaker {
                errors.push(ValidationError {
                    message: format!(
                        "After {command}: an utterance by *{} is now by *{speaker}, so the \
                         output no longer lines up with the input",
                        before.speaker
                    ),
                    level: ValidityLevel::StructurallyComplete,
                });
                // These are not the same utterance, so anything further this
                // pair could be asked is meaningless.
                continue;
            }
            if before.has_terminator && now.main.content.terminator.is_none() {
                // Word for word what `validate_output` says for the same
                // event, because it IS the same event to an operator; what
                // changed is only when it counts as one.
                errors.push(ValidationError {
                    message: format!(
                        "After {command}: utterance by *{} lost its terminator",
                        before.speaker
                    ),
                    level: ValidityLevel::StructurallyComplete,
                });
            }
        }

        if kept < self.utterances.len() {
            errors.push(ValidationError {
                message: format!(
                    "After {command}: the output kept {kept} of the input's {} utterances",
                    self.utterances.len()
                ),
                level: ValidityLevel::StructurallyComplete,
            });
        }

        errors
    }
}

impl Clone for PostValidated {
    fn clone(&self) -> Self {
        Self {
            command: self.command,
            proof: self.proof.clone(),
        }
    }
}

impl Clone for OutputProof {
    fn clone(&self) -> Self {
        match self {
            Self::Gated {
                judgement,
                file,
                text,
            } => Self::Gated {
                judgement: judgement.clone(),
                file: file.clone(),
                // Carried across so a clone of an already-materialized proof
                // does not re-serialize, and so that a clone of a `for_test`
                // proof keeps the bytes the double supplied rather than
                // deriving fresh ones from its parse.
                text: clone_materialized(text),
            },
            Self::Declined { file, text } => Self::Declined {
                file: file.clone(),
                text: text.clone(),
            },
            Self::PassedThrough { source } => Self::PassedThrough {
                source: source.clone(),
            },
        }
    }
}

impl PartialEq for PostValidated {
    /// Two proofs are equal when they are the same command's output over the
    /// same document.
    ///
    /// The materialization cache is deliberately not compared: it is DERIVED
    /// from the model, so whether one side happens to have been serialized
    /// already is a fact about who has read it, not about the documents.
    fn eq(&self, other: &Self) -> bool {
        self.command == other.command && self.proof == other.proof
    }
}

impl PartialEq for OutputProof {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (
                Self::Gated {
                    judgement,
                    file: mine,
                    ..
                },
                Self::Gated {
                    judgement: other_judgement,
                    file: theirs,
                    ..
                },
                // The judgement is compared as well as the document: what a
                // proof CLAIMS is part of what it is, so the same bytes
                // admitted on different grounds are not the same proof.
            ) => judgement == other_judgement && mine.document() == theirs.document(),
            // The MODEL, for the same reason the gated arm compares one: a
            // declined proof's bytes are serialized from its model at
            // construction, so comparing the model and comparing the bytes
            // answer identically, and the model is what the proof is about.
            (Self::Declined { file: mine, .. }, Self::Declined { file: theirs, .. }) => {
                mine.document() == theirs.document()
            }
            (Self::PassedThrough { source: mine }, Self::PassedThrough { source: theirs }) => {
                mine.source() == theirs.source()
            }
            // Written out rather than a catch-all so a fourth route to a proof
            // has to say what it compares equal to.
            (Self::Gated { .. }, Self::Declined { .. } | Self::PassedThrough { .. })
            | (Self::Declined { .. }, Self::Gated { .. } | Self::PassedThrough { .. })
            | (Self::PassedThrough { .. }, Self::Gated { .. } | Self::Declined { .. }) => false,
        }
    }
}

/// Why a command's output was refused.
///
/// Carries the bar the output was judged against, the command whose output
/// failed, and every failure the judgement found, so the operator sees what
/// broke rather than a count. Rendered into the per-file error a job reports.
#[derive(Debug, Clone, thiserror::Error)]
#[error("{command} post-validation failed ({}): {}", .findings.bar(), .findings.render())]
pub(crate) struct PostValidationFailure {
    /// The command whose own output failed its gate.
    pub(crate) command: ReleasedCommand,
    /// The bar the output was judged against (complete construction, or
    /// construction plus preservation; the message says which, so a reader is
    /// never told a document failed a bar it was never held to) and every
    /// failure the judgement found, never empty.
    findings: OutputFindings,
}

impl PostValidationFailure {
    /// `command`'s output refused by complete construction admission, after
    /// the `prior` findings of any earlier check.
    pub(crate) fn construction(
        command: ReleasedCommand,
        prior: Vec<Finding>,
        failure: &ValidationFailure,
    ) -> Self {
        Self {
            command,
            findings: OutputFindings::of_construction_refusal(
                JudgementBar::Construction,
                prior,
                failure,
            ),
        }
    }

    /// Preserve producer-failure classification at the public server
    /// boundary, with the findings still typed so a reporter can bound them.
    pub(crate) fn into_server_error(self) -> crate::error::ServerError {
        let OutputFindings {
            bar,
            findings: Findings { first, rest },
        } = self.findings;
        crate::error::ServerError::OutputAdmission {
            command: self.command,
            details: crate::error::OutputAdmissionRefusal::Judged { bar, first, rest },
        }
    }
}

/// The abbreviation merge produced a document that fails the judgement its
/// unmerged predecessor passed.
///
/// # Why the unmerged proof is in here
///
/// The transition CONSUMES the proof it merges, so without this the caller
/// could not fall back to the admissible output it was already holding, and a
/// cosmetic flag could turn a file with a valid judged output into a total
/// per-file failure with nothing written at all. That is reachable rather than
/// theoretical: `merge_abbreviations` edits the main tier and does not touch
/// `%mor`, so collapsing `F B I` into `FBI` in a morphotag output leaves three
/// `%mor` items against one word, which is exactly what `validate_output`
/// refuses. Pinned by
/// `a_merge_that_breaks_the_gate_hands_back_the_unmerged_proof`.
///
/// Deciding what to DO about it is the caller's, not this type's: writing the
/// unmerged output and failing the file are both defensible, and they differ
/// per seam. All five call sites currently fail the file, and each says so.
#[derive(Debug, thiserror::Error)]
#[error(
    "the abbreviation merge produced a document that fails its own gate \
         (the unmerged output is still admissible): {failure}"
)]
pub(crate) struct AbbreviationMergeRefused {
    /// The proof the merge was applied TO. Still admissible, still writable.
    pub(crate) unmerged: PostValidated,
    /// Why the MERGED document was refused.
    pub(crate) failure: PostValidationFailure,
}

/// What one judgement concluded about one model, before any caller decides
/// whether a refusal is a failure or a diagnosis.
///
/// The model comes back on refusal, so [`PostValidated::produced`] can write
/// it; the refusing transitions drop it.
enum Assessment {
    Admitted(OutputDocument),
    Refused {
        document: ChatFile,
        findings: OutputFindings,
    },
}

impl PostValidated {
    /// Run the post-validation gate over a command's finished output.
    ///
    /// Complete construction and command-specific completion are required;
    /// callers cannot choose a weaker validity level.
    ///
    /// This is the BORROWING form, and it is a one-clone wrapper over
    /// [`Self::gate_owned`]: the proof has to keep the model it judged, so a
    /// caller that only lends one forces a copy. Every caller that owns its
    /// model and drops it straight afterwards should call `gate_owned`
    /// instead; the two transitions below do, and so used to pay a
    /// whole-document clone to hand back a model they had just been given.
    pub(crate) fn gate(
        file: &ChatFile,
        command: ReleasedCommand,
    ) -> Result<Self, PostValidationFailure> {
        Self::gate_owned(file.clone(), command)
    }

    /// [`Self::gate`] for a caller that OWNS the model it is having judged.
    ///
    /// The evidence path proper. Nothing is serialized here: validation is
    /// what a transition owes, and the bytes are derived from this model when
    /// somebody actually asks for them. See [`OutputProof::Gated::text`].
    pub(crate) fn gate_owned(
        file: ChatFile,
        command: ReleasedCommand,
    ) -> Result<Self, PostValidationFailure> {
        Self::judge(file, Judgement::Admitted, command)
    }

    /// Judge output our OWN producer generated, and keep it either way.
    ///
    /// The same judgement as [`Self::gate_owned`], at the same bar, and
    /// infallible: a model that passes is an admitted [`PostValidated`], and
    /// one that does not is a [`DiagnosedOutput`], carrying the model and every
    /// finding, to be written with them. See the module docs for why this is right for a
    /// generating producer and wrong for a command that transforms submitted
    /// CHAT, which keeps the strict gate.
    ///
    /// Only generating producers call this: transcription, at CHAT assembly
    /// and again on its final document. Nothing that reads CHAT a user
    /// submitted may, because there a refusal is the right answer.
    pub(crate) fn produced(file: ChatFile, command: ReleasedCommand) -> ProducedOutput {
        let judgement = Judgement::Admitted;
        match Self::assess(file, &judgement, command) {
            Assessment::Admitted(file) => ProducedOutput::Admitted(Self {
                command,
                proof: OutputProof::Gated {
                    judgement,
                    file: Box::new(file),
                    text: OnceLock::new(),
                },
            }),
            Assessment::Refused { document, findings } => {
                ProducedOutput::Diagnosed(DiagnosedOutput {
                    command,
                    document: Box::new(DiagnosedDocument {
                        file: document,
                        text: OnceLock::new(),
                        findings,
                    }),
                })
            }
        }
    }

    /// Judge a generated document a per-utterance stage edited everywhere but
    /// at the `held_out` utterances, which carry the findings it was
    /// diagnosed for and which the stage left as they were.
    ///
    /// Admitted if it passes, like [`Self::produced`]. Otherwise it is
    /// diagnosed only if the document WITHOUT the held-out utterances passes:
    /// then every finding is still theirs, and the stage added none of its
    /// own. If that remainder fails too, the stage broke an utterance it was
    /// given, and its output is refused with the remainder's findings, just
    /// as the strict gate refuses an admitted document's stage output; the
    /// caller keeps the document from before the stage.
    pub(crate) fn produced_outside(
        file: ChatFile,
        held_out: &HeldOutInOutput,
        command: ReleasedCommand,
    ) -> Result<ProducedOutput, PostValidationFailure> {
        let judgement = Judgement::Admitted;
        let (document, findings) = match Self::assess(file, &judgement, command) {
            Assessment::Admitted(file) => {
                return Ok(ProducedOutput::Admitted(Self {
                    command,
                    proof: OutputProof::Gated {
                        judgement,
                        file: Box::new(file),
                        text: OnceLock::new(),
                    },
                }));
            }
            Assessment::Refused { document, findings } => (document, findings),
        };
        let mut remainder = document.clone();
        let mut ordinal = 0;
        remainder.lines.retain(|line| match line {
            Line::Utterance(_) => {
                let keep = !held_out.contains(ordinal);
                ordinal += 1;
                keep
            }
            _ => true,
        });
        match Self::assess(remainder, &judgement, command) {
            Assessment::Admitted(_) => Ok(ProducedOutput::Diagnosed(DiagnosedOutput {
                command,
                document: Box::new(DiagnosedDocument {
                    file: document,
                    text: OnceLock::new(),
                    findings,
                }),
            })),
            Assessment::Refused {
                findings: added, ..
            } => Err(PostValidationFailure {
                command,
                findings: added,
            }),
        }
    }

    /// Admit comparison output with complete construction and preservation.
    ///
    /// `input` is the census of the document the output DESCENDS from, taken
    /// before the command edited it. Preservation adds constraints; it never
    /// exempts invalid CHAT from Chatter's complete construction admission.
    pub(crate) fn preserving(
        input: UtteranceCensus,
        output: ChatFile,
        command: ReleasedCommand,
    ) -> Result<Self, PostValidationFailure> {
        Self::judge(output, Judgement::Preserved(input), command)
    }

    /// Run one [`Judgement`] over a model and keep the model it judged.
    ///
    /// The single place a `Gated` proof is built, so the judgement a proof
    /// records is always the judgement that was actually run over it, and the
    /// two transitions below re-run it by handing back the same value.
    fn judge(
        file: ChatFile,
        judgement: Judgement,
        command: ReleasedCommand,
    ) -> Result<Self, PostValidationFailure> {
        let file = Self::judge_document(file, &judgement, command)?;
        Ok(Self {
            command,
            proof: OutputProof::Gated {
                judgement,
                file: Box::new(file),
                text: OnceLock::new(),
            },
        })
    }

    fn judge_document(
        file: ChatFile,
        judgement: &Judgement,
        command: ReleasedCommand,
    ) -> Result<OutputDocument, PostValidationFailure> {
        match Self::assess(file, judgement, command) {
            Assessment::Admitted(file) => Ok(file),
            Assessment::Refused { findings, .. } => {
                Err(PostValidationFailure { command, findings })
            }
        }
    }

    /// Run one judgement and say what it concluded, keeping the model whichever
    /// way it went. The single judgement every transition runs.
    fn assess(file: ChatFile, judgement: &Judgement, command: ReleasedCommand) -> Assessment {
        let gate_errors: Vec<ValidationError> = match &judgement {
            Judgement::Admitted => {
                let mut errors = Vec::new();
                // Additional command-specific completion checks.
                if let Err(output_errors) = validate_output(&file, command.as_str()) {
                    errors.extend(output_errors);
                }
                errors
            }
            // Preservation adds constraints to complete construction below.
            Judgement::Preserved(input) => input.losses_in(&file, command),
            Judgement::Declined => Vec::new(),
        };
        let errors: Vec<Finding> = gate_errors.into_iter().map(gate_finding).collect();

        // This is the authoritative write admission. Completion and
        // preservation checks above may add constraints, never weaken it.
        // Construction admission validates the actual typed output, preserves
        // recorded recovery, and never reparses its serialized CHAT.
        let checked = file.validate_construction_with_policy(
            ValidationPolicy::new(
                talkbank_model::RuleSelection::new(),
                AlignmentValidation::IncludeTierAlignment,
            ),
            &talkbank_model::NullErrorSink,
            TranscriptName::Anonymous,
        );
        let file = match checked {
            Ok(file) => file,
            Err(failure) => {
                let findings =
                    OutputFindings::of_construction_refusal(judgement.bar(), errors, &failure);
                return Assessment::Refused {
                    document: failure.into_unchecked(),
                    findings,
                };
            }
        };

        match Findings::of(errors) {
            None => Assessment::Admitted(OutputDocument::Checked(file)),
            Some(findings) => Assessment::Refused {
                document: file.into_unchecked(),
                findings: OutputFindings {
                    bar: judgement.bar(),
                    findings,
                },
            },
        }
    }

    /// Return unchanged, strictly admitted original bytes.
    /// The capability couples those bytes to their exact parsed model, so a
    /// caller cannot independently assert validity or substitute another text.
    pub(crate) fn pass_through(
        source: batchalign_transform::AdmittedSourceChat<'_>,
        command: ReleasedCommand,
    ) -> Self {
        Self {
            command,
            proof: OutputProof::PassedThrough {
                source: Box::new(source.into_owned()),
            },
        }
    }

    /// Consume an admitted document, strip declared decision tiers and admit
    /// the actual result before serialization. Declined analysis does not
    /// waive CHAT validity, but has no analysis-completion claim to establish.
    pub(crate) fn declined_stripping_decision_tiers(
        file: ValidChatFile,
        command: ReleasedCommand,
    ) -> Result<Self, PostValidationFailure> {
        let mut file = file.into_unchecked();
        batchalign_transform::decisions::strip_decision_tiers(&mut file);
        let file = Self::judge_document(file, &Judgement::Declined, command)?;
        Ok(Self {
            command,
            // After checked construction, this declined route permits no later
            // cosmetic edits; serialize its final admitted model once.
            //
            // The MODEL is kept beside them, because "declined" does not mean
            // "there is nothing to continue from". compare reads morphotag's
            // document out of the proof and goes on comparing it in the AST,
            // and a CA main transcript, which morphotag declines to analyze, is
            // exactly a document compare must still compare. Written before
            // `file` because the serialization borrows what the next field
            // moves.
            proof: OutputProof::Declined {
                text: to_chat_string(file.document()),
                file: Box::new(file),
            },
        })
    }

    /// Merge single-letter abbreviations and re-run the gate over the merged
    /// MODEL, so the bytes returned are bytes a gate has judged.
    ///
    /// The writers used to call `merge_abbreviations_in_chat_text` on
    /// `as_str()` and write ITS result, which put a transform after the proof
    /// and made the proof describe a document that never reached disk. The
    /// merge is a step inside the gate now: it runs on the MODEL the proof
    /// carries and is re-judged under the SAME [`Judgement`] and for the SAME
    /// command that proof records, so the merge cannot lower the bar it is
    /// judged against, and a compare output is re-checked for preservation
    /// against the input census rather than against a level nothing admitted.
    ///
    /// # A refusal hands the unmerged proof BACK
    ///
    /// See [`AbbreviationMergeRefused`]: the merge is cosmetic and can break a
    /// document that was fine, so losing the proof it was applied to would
    /// turn a valid output into nothing written. The whole-document clone
    /// below is what that fallback costs, once per merged file, and it buys
    /// the only alternative to discarding an admissible output.
    ///
    /// Nothing is parsed. Until 2026-09-07 this re-parsed `self.text` and threw
    /// the parse errors away, so the re-gate's L0 rung was handed an empty
    /// error list and could not have refused anything, and the model merged was
    /// the parser's recovery of our own bytes rather than the model the gate
    /// had judged.
    ///
    /// # A pass-through is returned untouched, and that is the POLICY
    ///
    /// The merge is a policy applied to what the command WROTE. A document
    /// the command did not modify has no output for the merge to be a part
    /// of, so it is left exactly as it arrived and the tree it is written back
    /// into stays byte-identical. That is what pass-through means, and it is
    /// what `@Options: dummy`, `NoAlign`, a CA document a command declines to
    /// touch, and a document with no collectible payloads all get.
    ///
    /// This is a deliberate narrowing of the previous behaviour, where the
    /// merge ran on every success including those, because it ran on the
    /// finished TEXT at the writer rather than on a proof. Pinned by
    /// `merging_abbreviations_leaves_a_pass_through_byte_identical` below, and
    /// documented for operators in
    /// `book/src/batchalign/reference/command-io.md`.
    pub(crate) fn with_abbreviations_merged(self) -> Result<Self, Box<AbbreviationMergeRefused>> {
        let command = self.command;
        let (judgement, file, text) = match self.proof {
            OutputProof::Gated {
                judgement,
                file,
                text,
            } => (judgement, file, text),
            proof @ (OutputProof::Declined { .. } | OutputProof::PassedThrough { .. }) => {
                return Ok(Self { command, proof });
            }
        };
        let mut merged = file.clone().into_unchecked();
        merge_abbreviations(&mut merged);
        Self::judge(merged, judgement.clone(), command).map_err(|failure| {
            // Boxed: it carries a whole proof, and an error that large would
            // be copied through every `Result` it passes along.
            Box::new(AbbreviationMergeRefused {
                // Rebuilt from the parts the merge did not touch, cache
                // included, so the caller gets back exactly the proof it
                // handed in rather than an equivalent one.
                unmerged: Self {
                    command,
                    proof: OutputProof::Gated {
                        judgement,
                        file,
                        text,
                    },
                },
                failure,
            })
        })
    }

    /// Stamp the run's provenance comment onto the MODEL and re-run the gate,
    /// so the bytes returned are bytes a gate has judged.
    ///
    /// `align` used to build its proof, throw it away, serialize the model
    /// again, inject the comment into that TEXT, and hand the writer a bare
    /// `String` which the writer then re-gated at a level nobody had admitted
    /// anything at. Two of those steps were a defect each: the written bytes
    /// were not the proven bytes, and the second gate refused documents the
    /// first had deliberately let through. The stamp is a transition on the
    /// proof now, applied to the MODEL that proof carries and re-judged under
    /// the SAME [`Judgement`] and for the SAME command it records, so it
    /// cannot lower the bar it is judged against. Nothing is parsed, for the
    /// reason [`Self::with_abbreviations_merged`] gives.
    ///
    /// Unlike the merge, a refusal here does not hand the pre-stamp proof
    /// back, and that is deliberate rather than an oversight: a document
    /// written without its `[fc-ba3 ...]` line is not a lesser version of the
    /// same output, it is one the provenance gate can no longer recognise on
    /// the next run, so there is no fallback for a caller to choose.
    ///
    /// A pass-through is returned untouched, for the same reason
    /// [`Self::with_abbreviations_merged`] returns one untouched: the command
    /// applied nothing, so there is no run for a provenance line to describe.
    /// This is what makes `NoAlign`'s documented "strict pass-through, zero
    /// modifications" literally true; it used to acquire a `@Comment` line.
    pub(crate) fn with_provenance_injected(
        self,
        comment: &crate::provenance::ProvenanceComment,
    ) -> Result<Self, PostValidationFailure> {
        let command = self.command;
        let (judgement, file) = match self.proof {
            OutputProof::Gated {
                judgement, file, ..
            } => (judgement, file),
            proof @ (OutputProof::Declined { .. } | OutputProof::PassedThrough { .. }) => {
                return Ok(Self { command, proof });
            }
        };
        let mut file = file.into_unchecked();
        crate::provenance::inject_provenance(&mut file, comment);
        Self::judge(file, judgement, command)
    }

    /// The command whose output these bytes are.
    ///
    /// The writer reads the command from HERE rather than being told it
    /// separately, so there is no second place for the name to be written down
    /// and no way for the two to disagree.
    pub(crate) fn command(&self) -> ReleasedCommand {
        self.command
    }

    /// Borrow the validated CHAT text, serializing the judged model if this is
    /// the first time anyone has asked.
    ///
    /// THE materialization point for a proof that is being read rather than
    /// consumed, and the reason the transitions above are free: an aligned
    /// file is judged three times and serialized once, at the writer, instead
    /// of three times with the first two dropped unread.
    ///
    /// Call it only where the bytes are genuinely wanted. A caller that will
    /// discard them (a debug dump that is switched off, say) should ask
    /// whether it wants them BEFORE asking for them.
    pub(crate) fn as_str(&self) -> &str {
        match &self.proof {
            OutputProof::Gated { file, text, .. } => {
                text.get_or_init(|| to_chat_string(file.document()))
            }
            OutputProof::Declined { text, .. } => text,
            OutputProof::PassedThrough { source } => source.source(),
        }
    }

    /// Take ownership of the validated CHAT text.
    ///
    /// Used by consumers that are not the writer (comparison artifacts, the
    /// transcribe pipeline's intermediate stage), which legitimately need the
    /// string. This does not weaken the gate: the writer seams take the proof
    /// itself, so a bare `String` still cannot reach disk.
    pub(crate) fn into_text(self) -> String {
        match self.proof {
            OutputProof::Declined { text, .. } => text,
            OutputProof::PassedThrough { source } => source.into_source(),
            OutputProof::Gated { file, text, .. } => match text.into_inner() {
                // Already materialized by an earlier `as_str`; reuse rather
                // than serialize a second time.
                Some(materialized) => materialized,
                // Nobody has asked for bytes yet, so this is the proof's one
                // and only serialization.
                None => to_chat_string(file.document()),
            },
        }
    }

    /// Take ownership of the DOCUMENT this proof is about, for a consumer that
    /// continues in the AST instead of writing bytes.
    ///
    /// This is [`Self::into_text`]'s counterpart and the one a downstream
    /// ANALYSIS should reach for. compare is the caller: it morphotags the main
    /// transcript and then compares it, and comparing is done on a model. It
    /// used to take the text and parse it again with [`parse_lenient`], so the
    /// document it compared was the parser's recovery of our own bytes rather
    /// than the document morphotag produced and the gate judged, and a parse
    /// error on that path was a `warn!` rather than an answer.
    ///
    /// Every variant carries its admitted model, including unchanged source.
    /// Consuming the proof releases editing authority, not write authority.
    ///
    /// [`parse_lenient`]: batchalign_transform::parse::parse_lenient
    pub(crate) fn into_judged_document(self) -> ChatFile {
        match self.proof {
            OutputProof::Gated { file, .. } => file.into_unchecked(),
            OutputProof::Declined { file, .. } => file.into_unchecked(),
            OutputProof::PassedThrough { source } => source.into_valid_file().into_unchecked(),
        }
    }

    /// Read the admitted document without mutation or serialization.
    pub(crate) fn document(&self) -> &ChatFile {
        match &self.proof {
            OutputProof::Gated { file, .. } | OutputProof::Declined { file, .. } => file.document(),
            OutputProof::PassedThrough { source } => source.document(),
        }
    }

    /// Test-only route, for the fake `WorkerGateway` doubles.
    ///
    /// See the module docs: these doubles replace a gateway whose production
    /// implementation runs the gate, so the double is upstream of it and never
    /// builds a `ChatFile` to gate.
    ///
    /// It carries a GATED proof, not an unchanged one, because that is what
    /// the real gateway returns. This matters: `with_abbreviations_merged`
    /// returns a pass-through untouched, so a double claiming "unchanged"
    /// would make the write path skip the merge in tests while running it in
    /// production, which is the double modelling a different seam from the one
    /// it stands in for.
    #[cfg(test)]
    pub(crate) fn for_test(text: impl Into<String>, command: ReleasedCommand) -> Self {
        let text = text.into();
        // The double has no model and a `Gated` proof has one, so this is where
        // the pair is stood up. Parsing here is not the re-parse the module
        // bans: that ban is about re-deriving a command's own output from its
        // own bytes, and this string is one a test wrote.
        let parser = crate::chat_parser();
        let (file, _parse_errors) = batchalign_transform::parse::parse_lenient(&parser, &text);
        // The double's OWN bytes are pre-loaded into the materialization
        // cache, so READING this proof hands back exactly what the test wrote
        // rather than a round trip through the parser and the serializer. The
        // real gateway's bytes and its model always agree; a double's need
        // not, and the write-gate tests in `recipe_runner::runtime` assert on
        // bytes they supplied, several of which are CHAT fragments with no
        // `@UTF8` / `@Begin` that would not survive a round trip.
        //
        // That holds for READS ONLY, and the difference matters. Every
        // transition above consumes the proof and rebuilds it around the model
        // it just judged, with a FRESH cache, so the bytes after a transition
        // are the serialization of this parse and not what was passed in. A
        // double whose text does not round-trip must therefore be read, never
        // transitioned; put a document through `with_abbreviations_merged` or
        // `with_provenance_injected` in a test and it will come back
        // re-serialized. This comment said "reading this proof hands back
        // exactly what the test wrote" with no such qualification until
        // 2026-09-07, which reads as a promise about the value rather than
        // about one method of it.
        let materialized = OnceLock::new();
        // Infallible on a cell made one line above.
        let _ = materialized.set(text);
        Self {
            command,
            proof: OutputProof::Gated {
                judgement: Judgement::Admitted,
                file: Box::new(OutputDocument::Double(file)),
                text: materialized,
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use batchalign_transform::parse::{TreeSitterParser, parse_lenient};
    use talkbank_model::model::Line;

    /// A minimal fully valid CHAT file with a terminator.
    const VALID: &str = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tCHI Target_Child\n\
@ID:\teng|test|CHI|3;|male|||Target_Child|||\n*CHI:\thello world .\n@End\n";

    /// An invalid variant of VALID; recovery does not authorize writing it.
    const NO_TERMINATOR: &str = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tCHI Target_Child\n\
@ID:\teng|test|CHI|3;|male|||Target_Child|||\n*CHI:\thello world\n@End\n";

    fn parse(text: &str) -> ChatFile {
        let parser = TreeSitterParser::new().expect("grammar loads");
        let (file, _errors) = parse_lenient(&parser, text);
        file
    }

    #[test]
    fn output_proof_is_a_compact_ownership_handle() {
        let proof = std::mem::size_of::<PostValidated>();
        let source = std::mem::size_of::<batchalign_transform::AdmittedSourceChat<'static>>();
        assert!(
            proof <= 128,
            "output handle is {proof} bytes; boxed source payload is {source}"
        );
        eprintln!("output handle: {proof} bytes; source payload: {source} bytes");
    }

    fn source(text: &str) -> batchalign_transform::AdmittedSourceChat<'_> {
        crate::pipeline::text_infer::admit_retained_text(
            &crate::chat_parser(),
            text,
            TranscriptName::Anonymous,
        )
        .expect("the source control must be completely valid")
    }

    /// Complete construction and command completion authorize output bytes.
    #[test]
    fn gate_admits_output_that_still_validates() {
        let file = parse(VALID);
        let proof = PostValidated::gate(&file, ReleasedCommand::Utseg)
            .expect("a clean file must pass its own output gate");
        assert!(proof.as_str().contains("*CHI:"));
    }

    /// RED FIRST: an output that lost a terminator must be REFUSED, not
    /// warned about. This is the whole point of the type; before this change
    /// the same input produced a `warn!` and a written file.
    #[test]
    fn gate_refuses_output_that_dropped_a_terminator() {
        let mut file = parse(VALID);
        for line in &mut file.lines {
            if let Line::Utterance(utt) = line {
                utt.main.content.terminator = None;
            }
        }
        let failure = PostValidated::gate(&file, ReleasedCommand::Utseg)
            .expect_err("an output that lost its terminator must be refused");
        assert_eq!(failure.command, ReleasedCommand::Utseg);
        let rendered = failure.to_string();
        assert!(
            rendered.contains("lost its terminator"),
            "the refusal must name what broke, got: {rendered}"
        );
    }

    /// No-work status cannot exempt invalid source from complete admission.
    #[test]
    fn invalid_source_cannot_acquire_pass_through_permission() {
        let text = "@UTF8\n@Begin\n*PAR:\thello .\n@End\n";
        let file = parse(text);
        assert!(
            PostValidated::gate(&file, ReleasedCommand::Utseg).is_err(),
            "precondition: this document does not satisfy L1"
        );
        assert!(
            crate::pipeline::text_infer::admit_retained_text(
                &crate::chat_parser(),
                text,
                TranscriptName::Anonymous,
            )
            .is_err()
        );
    }

    /// RED FIRST: a pass-through must carry the input's OWN bytes. It used to
    /// re-serialize the parsed model, so a document the docs call unchanged
    /// shipped through a serializer no gate had judged. The trailing spaces
    /// here are the cheapest observable difference a round trip removes.
    #[test]
    fn pass_through_carries_the_original_bytes_not_a_reserialization() {
        let text = VALID.replace("*CHI:", "@Comment:\tkept   \n*CHI:");
        let proof = PostValidated::pass_through(source(&text), ReleasedCommand::Utseg);
        assert_eq!(
            proof.as_str(),
            text.as_str(),
            "a pass-through must be byte-identical to its input"
        );
    }

    /// RED FIRST (2026-09-07): a declining command's proof must not carry the
    /// decision tiers an earlier align run wrote, and the constructor is what
    /// guarantees it.
    ///
    /// The strip and the declaration were paired by convention across three
    /// call sites, so a fourth would have shipped `%xalign` back out. The
    /// `pass_through` half of the assertion is the control: it is the same
    /// document down the other route, and it keeps the tiers, which is exactly
    /// why the two routes are different constructors.
    #[test]
    fn declining_a_document_strips_the_decision_tiers_a_previous_run_wrote() {
        let text = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tCHI Target_Child\n\
@ID:\teng|test|CHI|3;|male|||Target_Child|||\n*CHI:\thello world .\n\
%xalign:\tmonotonicity:end_clamped\n@End\n";
        let declined = PostValidated::declined_stripping_decision_tiers(
            crate::pipeline::text_infer::admit_retained_text(
                &crate::chat_parser(),
                text,
                TranscriptName::Anonymous,
            )
            .expect("the retained source is valid")
            .into_valid_file(),
            ReleasedCommand::Morphotag,
        )
        .expect("removing decision tiers preserves validity");
        assert!(
            !declined.as_str().contains("%xalign:"),
            "the constructor must apply the declared no-op, got: {}",
            declined.as_str()
        );
        assert!(
            declined.as_str().contains("*CHI:"),
            "only the decision tiers may go, got: {}",
            declined.as_str()
        );
        assert!(
            PostValidated::pass_through(source(text), ReleasedCommand::Morphotag)
                .as_str()
                .contains("%xalign:"),
            "control: a pass-through applies nothing, so it keeps them"
        );
    }

    /// An inherited defect is still invalid output, not a preservation waiver.
    #[test]
    fn preservation_cannot_exempt_invalid_output_from_complete_admission() {
        let input = parse(NO_TERMINATOR);
        assert!(
            PostValidated::gate(&input, ReleasedCommand::Compare).is_err(),
            "precondition: a level gate refuses this document"
        );
        let failure = PostValidated::preserving(
            UtteranceCensus::of(&input),
            input.clone(),
            ReleasedCommand::Compare,
        )
        .expect_err("preserving an invalid input does not authorize invalid output");
        assert!(failure.findings.errors().next().is_some());
    }

    /// RED FIRST (2026-09-07 review, item 1): the same output IS refused when
    /// its input had the terminator, so the check fires on a real loss.
    ///
    /// Read with the test above, these two differ only in the input, which is
    /// what makes either of them evidence: a check that ignored the input would
    /// fail one of them whichever way it leaned.
    #[test]
    fn preserving_refuses_an_output_that_lost_a_terminator_its_input_had() {
        let failure = PostValidated::preserving(
            UtteranceCensus::of(&parse(VALID)),
            parse(NO_TERMINATOR),
            ReleasedCommand::Compare,
        )
        .expect_err("an output that lost a terminator its input had must be refused");
        assert_eq!(failure.findings.bar(), JudgementBar::Preservation);
        let rendered = failure.to_string();
        assert!(
            rendered.contains("lost its terminator"),
            "the refusal must name what broke, got: {rendered}"
        );
        assert!(
            !rendered.contains("must still satisfy"),
            "a preserved refusal must not report a bar the input was never held to: {rendered}"
        );
    }

    /// An utterance the command DROPPED is a loss too, and the count is what
    /// notices it.
    #[test]
    fn preserving_refuses_an_output_that_dropped_an_utterance() {
        let two = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tCHI Target_Child\n\
@ID:\teng|test|CHI|3;|male|||Target_Child|||\n*CHI:\thello world .\n*CHI:\tbye now .\n@End\n";
        let failure = PostValidated::preserving(
            UtteranceCensus::of(&parse(two)),
            parse(VALID),
            ReleasedCommand::Compare,
        )
        .expect_err("an output with fewer utterances than its input must be refused");
        assert!(
            failure
                .to_string()
                .contains("kept 1 of the input's 2 utterances"),
            "the refusal must say what went missing, got: {failure}"
        );
    }

    /// The correspondence between the two documents is positional, so it is
    /// CHECKED rather than assumed: an output whose utterances no longer line
    /// up with the input is refused instead of having two unrelated utterances
    /// silently compared.
    #[test]
    fn preserving_refuses_an_output_whose_utterances_no_longer_line_up() {
        let other_speaker = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tMOT Mother\n\
@ID:\teng|test|MOT|||||Mother|||\n*MOT:\thello world .\n@End\n";
        let failure = PostValidated::preserving(
            UtteranceCensus::of(&parse(VALID)),
            parse(other_speaker),
            ReleasedCommand::Compare,
        )
        .expect_err("an output that no longer lines up with its input must be refused");
        assert!(
            failure.to_string().contains("no longer lines up"),
            "the refusal must say the correspondence broke, got: {failure}"
        );
    }

    /// Abbreviation merging must retain preservation checks in addition to
    /// complete construction. This valid fixture ensures the merge runs.
    #[test]
    fn a_preserved_proof_is_still_judged_by_preservation_after_the_merge() {
        let text = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tCHI Target_Child\n\
@ID:\teng|test|CHI|3;|male|||Target_Child|||\n*CHI:\tF B I here .\n@End\n";
        let file = parse(text);
        let proof = PostValidated::preserving(
            UtteranceCensus::of(&file),
            file.clone(),
            ReleasedCommand::Compare,
        )
        .expect("nothing was lost: the output IS the input");
        let merged = proof
            .with_abbreviations_merged()
            .expect("the merge must be judged the way the document that reached it was");
        assert!(
            merged.as_str().contains("FBI"),
            "the merge must still have run, got: {}",
            merged.as_str()
        );
    }

    /// RED FIRST (2026-09-07 review, item 5): a merge that breaks the gate
    /// hands the UNMERGED proof back, so a cosmetic transform cannot destroy an
    /// admissible output.
    ///
    /// Reachable rather than contrived: `merge_abbreviations` edits the main
    /// tier and leaves `%mor` alone, so collapsing `F B I` into `FBI` in a
    /// morphotag output leaves four `%mor` items against two words, which is
    /// exactly what `validate_output` refuses. Before this the transition had
    /// consumed the proof and the caller had nothing left to fall back to.
    #[test]
    fn a_merge_that_breaks_the_gate_hands_back_the_unmerged_proof() {
        let text = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tCHI Target_Child\n\
@ID:\teng|test|CHI|3;|male|||Target_Child|||\n*CHI:\tF B I .\n\
%mor:\tn|F n|B n|I .\n@End\n";
        let proof = PostValidated::gate(&parse(text), ReleasedCommand::Morphotag)
            .expect("precondition: the unmerged morphotag output passes its own gate");

        let refused = proof
            .with_abbreviations_merged()
            .expect_err("the merged document desynchronises %mor and must be refused");
        assert!(
            refused.failure.to_string().contains("%mor has"),
            "the failure must name what the merge broke, got: {}",
            refused.failure
        );
        assert!(
            refused.to_string().contains("abbreviation merge"),
            "the refusal must name the merge as the cause, got: {refused}"
        );
        assert!(
            refused.unmerged.as_str().contains("F B I"),
            "the unmerged proof must come back intact, got: {}",
            refused.unmerged.as_str()
        );
    }

    /// RED FIRST: the abbreviation merge is a step INSIDE the gate, so the
    /// bytes it returns are bytes the gate judged. Before this the writer ran
    /// the merge on `as_str()` and wrote the RESULT, which no gate had seen.
    #[test]
    fn merging_abbreviations_returns_a_proof_over_the_merged_bytes() {
        let text = "@UTF8\n@Begin\n@Languages:\teng\n@Participants:\tCHI Target_Child\n\
@ID:\teng|test|CHI|3;|male|||Target_Child|||\n*CHI:\tF B I here .\n@End\n";
        let file = parse(text);
        let proof =
            PostValidated::gate(&file, ReleasedCommand::Utseg).expect("the input is valid at L1");
        assert!(proof.as_str().contains("F B I"), "precondition: unmerged");
        let merged = proof
            .with_abbreviations_merged()
            .expect("the merged document still satisfies its own gate");
        assert!(
            merged.as_str().contains("FBI"),
            "the merge must have been applied to the bytes the proof carries, got: {}",
            merged.as_str()
        );
    }

    /// A pass-through is not re-written by the merge: the command applied
    /// nothing, so there is no output for the merge to be a part of.
    #[test]
    fn merging_abbreviations_leaves_a_pass_through_byte_identical() {
        let text = VALID.replace("hello world", "F B I");
        let merged = PostValidated::pass_through(source(&text), ReleasedCommand::Utseg)
            .with_abbreviations_merged()
            .expect("a pass-through cannot fail a gate it does not run");
        assert_eq!(merged.as_str(), text);
    }

    /// Checked construction must reject an invalid manually assembled word.
    /// This is constructor-boundary evidence, not CHAT corpus coverage.
    #[test]
    fn whitespace_cannot_be_smuggled_through_a_typed_word() {
        use talkbank_model::model::{TierContentItems, UtteranceContent, Word};

        let mut file = parse(VALID);
        for line in &mut file.lines {
            if let Line::Utterance(utt) = line {
                utt.main.content.content = TierContentItems::new(vec![UtteranceContent::Word(
                    Box::new(Word::simple("F B I")),
                )]);
            }
        }

        let failure = PostValidated::gate(&file, ReleasedCommand::Utseg)
            .expect_err("a manually assembled illegal word cannot authorize output");
        assert!(failure.to_string().contains("E243"));
        let first = failure.findings.first();
        assert_eq!(
            first.code.as_deref(),
            Some("E243"),
            "the code is a field of the finding"
        );
        assert_eq!(
            first.level,
            crate::api::FindingLevel::Construction,
            "a construction diagnostic is not graded at a gate level it was never checked at"
        );
        insta::assert_snapshot!(first.to_string(), @"E243 Word contains illegal whitespace characters");
        let error = failure.into_server_error();
        assert!(matches!(
            &error,
            crate::error::ServerError::OutputAdmission { .. }
        ));
        assert_eq!(
            crate::runner::util::classify_server_error(&error),
            crate::scheduling::FailureCategory::System
        );
        use axum::response::IntoResponse;
        assert_eq!(
            error.into_response().status(),
            axum::http::StatusCode::INTERNAL_SERVER_ERROR
        );
    }

    /// A transcribe-shaped generated document with one ASR token the CHAT
    /// rules refuse (`b2`, a digit inside a word). Built the way transcription
    /// builds it: a model, not a parse of text that could carry recovery.
    fn generated_with_invalid_word() -> ChatFile {
        use talkbank_model::model::{TierContentItems, UtteranceContent, Word};

        let mut file = parse(VALID);
        for line in &mut file.lines {
            if let Line::Utterance(utt) = line {
                utt.main.content.content = TierContentItems::new(vec![
                    UtteranceContent::Word(Box::new(Word::simple("hello"))),
                    UtteranceContent::Word(Box::new(Word::simple("b2"))),
                ]);
            }
        }
        file
    }

    /// RED FIRST (2026-10-06): output our own producer generated is written
    /// with its diagnostics, not refused. Before this, one ASR token made the
    /// whole transcript vanish behind a file error.
    #[test]
    fn a_producer_keeps_its_generated_output_with_every_finding() {
        let file = generated_with_invalid_word();
        let produced = PostValidated::produced(file, ReleasedCommand::Transcribe);
        let OutputReport::Diagnosed(report) = OutputReport::of(&produced, &[]) else {
            panic!("an invalid generated word must diagnose the output");
        };
        assert!(
            report
                .findings()
                .any(|finding| finding.code.as_deref() == Some("E220")),
            "every finding is reported by code, got: {report:?}"
        );
        assert!(report.shortfalls().is_empty(), "nothing was skipped yet");
        assert!(
            produced.as_str().contains("hello b2 ."),
            "the generated bytes are what is written, got: {}",
            produced.as_str()
        );
    }

    /// The SAME document is still refused by the strict gate a command that
    /// transforms submitted CHAT uses: validation is exactly as strict, only
    /// a generating producer's handling of the verdict differs.
    #[test]
    fn the_strict_gate_still_refuses_what_a_producer_keeps() {
        let failure =
            PostValidated::gate_owned(generated_with_invalid_word(), ReleasedCommand::Morphotag)
                .expect_err("a strict gate refuses the same document");
        assert!(
            failure
                .findings
                .errors()
                .any(|error| error.code.as_deref() == Some("E220")),
            "the refusal names the same finding, got: {failure}"
        );
    }

    /// A clean generated document is admitted by the producer transition; a
    /// diagnosed one is a different type, so it cannot be handed to a stage
    /// that requires admission.
    #[test]
    fn the_producer_transition_is_a_sum_of_admitted_and_diagnosed() {
        let admitted = PostValidated::produced(parse(VALID), ReleasedCommand::Transcribe);
        assert!(matches!(admitted, ProducedOutput::Admitted(_)));
        assert_eq!(OutputReport::of(&admitted, &[]), OutputReport::Clean);
        let diagnosed =
            PostValidated::produced(generated_with_invalid_word(), ReleasedCommand::Transcribe);
        assert!(matches!(diagnosed, ProducedOutput::Diagnosed(_)));
    }

    /// Shortfalls are reported whatever the document's standing: an admitted
    /// document with a shortfall is never reported clean, and a diagnosed one
    /// reports its findings and its shortfalls together.
    #[test]
    fn shortfalls_are_reported_whatever_the_standing() {
        let refused = Shortfall::StageNotApplied {
            stage: OptionalStage::UtteranceSegmentation,
            refusal: crate::api::StageRefusalRecord::judged(
                JudgementBar::Construction,
                &[crate::api::FileOutputDiagnostics::coded_finding(
                    "E999",
                    "synthetic",
                )],
            ),
        };
        let admitted = PostValidated::produced(parse(VALID), ReleasedCommand::Transcribe);
        let OutputReport::Diagnosed(report) =
            OutputReport::of(&admitted, std::slice::from_ref(&refused))
        else {
            panic!("a shortfall is never reported clean");
        };
        assert!(
            report.findings().next().is_none(),
            "the document itself passed"
        );
        assert_eq!(report.shortfalls(), std::slice::from_ref(&refused));
        assert!(
            refused
                .to_string()
                .starts_with("utterance segmentation not applied")
        );

        let diagnosed =
            PostValidated::produced(generated_with_invalid_word(), ReleasedCommand::Transcribe);
        let shortfalls = [
            Shortfall::StageSkipped {
                stage: OptionalStage::UtteranceSegmentation,
            },
            Shortfall::StageSkipped {
                stage: OptionalStage::Morphosyntax,
            },
        ];
        let OutputReport::Diagnosed(report) = OutputReport::of(&diagnosed, &shortfalls) else {
            panic!("findings are reported");
        };
        assert!(report.findings().next().is_some());
        assert_eq!(report.shortfalls().len(), 2);
    }

    /// A requested merge still runs on a diagnosed output, and the merged
    /// model is judged afresh by the producer transition.
    #[test]
    fn merging_a_diagnosed_output_judges_it_afresh() {
        use talkbank_model::model::{TierContentItems, UtteranceContent, Word};

        let mut file = generated_with_invalid_word();
        for line in &mut file.lines {
            if let Line::Utterance(utt) = line {
                utt.main.content.content = TierContentItems::new(
                    ["F", "B", "I", "b2"]
                        .into_iter()
                        .map(|word| UtteranceContent::Word(Box::new(Word::simple(word))))
                        .collect(),
                );
            }
        }
        let merged = PostValidated::produced(file, ReleasedCommand::Transcribe)
            .with_abbreviations_merged()
            .expect("a diagnosed output is never refused by the merge");
        assert!(merged.as_str().contains("FBI b2"), "{}", merged.as_str());
        assert!(
            matches!(merged, ProducedOutput::Diagnosed(_)),
            "the merge does not repair the finding"
        );
    }

    /// A recorded diagnosis is bounded: the count, a count per code and the
    /// first findings stay on the record; a longer list is written once, in
    /// full, to the sidecar, and a short one writes nothing.
    #[tokio::test]
    async fn recording_bounds_the_findings_and_writes_a_long_list_once() {
        let finding = |code: Option<&str>, n: usize| Finding {
            code: code.map(str::to_owned),
            level: crate::api::FindingLevel::StructurallyComplete,
            message: format!("finding {n}"),
        };
        let many: Vec<Finding> = (0..25)
            .map(|n| finding(if n % 5 == 0 { None } else { Some("E220") }, n))
            .collect();
        let dir = tempfile::tempdir().expect("tempdir");
        let sidecar = dir.path().join("diagnostics/out.cha.findings.json");
        let record = DiagnosticsDraft {
            findings: Some(OutputFindings {
                bar: JudgementBar::Construction,
                findings: Findings::of(many.clone()).expect("nonempty"),
            }),
            shortfalls: Vec::new(),
        }
        .record(&sidecar)
        .await;
        assert_eq!(record.finding_count(), 25);
        assert_eq!(
            record.first_findings().len(),
            crate::api::FileOutputDiagnostics::FIRST_FINDINGS
        );
        assert_eq!(
            record.findings.as_ref().expect("findings").findings_by_code,
            vec![
                crate::api::FindingCodeCount {
                    code: Some("E220".into()),
                    count: 20
                },
                crate::api::FindingCodeCount {
                    code: None,
                    count: 5
                },
            ]
        );
        assert_eq!(
            record.findings.as_ref().expect("findings").full_findings,
            crate::api::FullFindings::Sidecar {
                path: sidecar.to_string_lossy().into_owned()
            }
        );
        let written: Vec<Finding> =
            serde_json::from_slice(&std::fs::read(&sidecar).expect("sidecar")).expect("json");
        assert_eq!(written, many, "the sidecar holds the complete list");
        assert!(
            record
                .lines()
                .iter()
                .any(|line| line.contains("5 more finding(s)"))
        );

        let short = dir.path().join("diagnostics/short.cha.findings.json");
        let record = DiagnosticsDraft {
            findings: Some(OutputFindings {
                bar: JudgementBar::Construction,
                findings: Findings::of(many[..3].to_vec()).expect("nonempty"),
            }),
            shortfalls: Vec::new(),
        }
        .record(&short)
        .await;
        assert_eq!(
            record.findings.as_ref().expect("findings").full_findings,
            crate::api::FullFindings::Inline
        );
        assert!(!short.exists(), "a list that fits writes no sidecar");

        // A retry whose list fits leaves no stale sidecar from the earlier
        // attempt beside a record that does not name it.
        let retried = DiagnosticsDraft {
            findings: Some(OutputFindings {
                bar: JudgementBar::Construction,
                findings: Findings::of(many[..3].to_vec()).expect("nonempty"),
            }),
            shortfalls: Vec::new(),
        }
        .record(&sidecar)
        .await;
        assert_eq!(
            retried.findings.as_ref().expect("findings").full_findings,
            crate::api::FullFindings::Inline
        );
        assert!(
            !sidecar.exists(),
            "the earlier attempt's sidecar is removed"
        );
    }

    /// A sidecar that cannot be written is recorded as unwritten, with the
    /// bounded record intact; it never turns the written output into an
    /// error.
    #[tokio::test]
    async fn an_unwritable_sidecar_is_recorded_not_raised() {
        let dir = tempfile::tempdir().expect("tempdir");
        // A regular file where the sidecar's directory should be.
        let blocker = dir.path().join("diagnostics");
        std::fs::write(&blocker, b"not a directory").expect("blocker");
        let sidecar = blocker.join("out.cha.findings.json");
        let findings: Vec<Finding> = (0..25)
            .map(|n| crate::api::FileOutputDiagnostics::coded_finding("E220", &format!("f{n}")))
            .collect();
        let record = DiagnosticsDraft {
            findings: Some(OutputFindings {
                bar: JudgementBar::Construction,
                findings: Findings::of(findings).expect("nonempty"),
            }),
            shortfalls: Vec::new(),
        }
        .record(&sidecar)
        .await;
        assert_eq!(record.finding_count(), 25);
        assert_eq!(
            record.first_findings().len(),
            crate::api::FileOutputDiagnostics::FIRST_FINDINGS
        );
        let full = &record.findings.as_ref().expect("findings").full_findings;
        let crate::api::FullFindings::Unwritten { path, .. } = full else {
            panic!("expected an unwritten sidecar, got {full:?}");
        };
        assert_eq!(path, &sidecar.to_string_lossy());
        assert!(
            record
                .lines()
                .iter()
                .any(|line| line.contains("could not be written"))
        );
    }
}
