//! The CHILDES English MOR lexicon as a constraint on Stanza's part of speech.
//!
//! MOR+POST never let a tagger invent a category: MOR licenses the categories a
//! surface form may take from a curated lexicon, and POST only chooses among
//! them. Stanza picks from all seventeen UPOS tags with no such constraint, and
//! a sentence-final period is enough to make it read `whoops` as a plural noun
//! (lemma `whoop`). Withholding the period was measured and rejected (it costs
//! more structural analyses than it saves), so the constraint is applied where
//! MOR applies it: at the lexicon.
//!
//! This module derives, from the lexicon at a pinned `TalkBank/mor` commit,
//! the set of forms whose category is NOT in doubt: every entry for the form,
//! across every `.cut` file, licenses the same one of a small set of
//! categories, and (for nouns) MOR could not derive a different category from
//! a known base by a productive suffix. Those verdicts are embedded at compile
//! time (`data/eng_lexicon_verdicts.json`, regenerated by the
//! `gen_eng_lexicon_verdicts` example) and consumed by
//! [`crate::morphosyntax::invariants`], which overrides Stanza's UPOS only
//! where a verdict exists and Stanza disagrees with it. Ambiguous forms
//! (`well`, `back`, `whoop`) never produce a verdict and are never touched.
//!
//! The category set is deliberately small: a communicator (`co`) has no
//! features, and a noun's only feature is its number, which the lexicon entry
//! itself states. Categories whose features Stanza computed under the wrong
//! part of speech (a verb's tense and person) cannot be repaired from the
//! lexicon alone and are not attempted here.

use std::collections::{HashMap, HashSet};
use std::sync::LazyLock;

/// One entry of a MOR `.cut` lexicon file: `form {[scat cat] ...} "stem"`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MorEntry {
    /// The surface form, exactly as written in the lexicon.
    pub form: String,
    /// The `[scat ...]` value: the category of a word entry, or the kind of
    /// affix (`pfx`, `adjsfx`) for an affix entry.
    pub scat: Option<String>,
    /// The `[dcat result:base]` value of a derivational affix entry: the
    /// category it produces and the category it attaches to.
    pub dcat: Option<String>,
    /// `false` when the entry carries `[bare no]`: an allomorph that never
    /// attaches directly to a bare stem (`ab` of `-able` before `-ility`).
    pub attaches_to_bare_stem: bool,
    /// The quoted stem with its affix markers (`dog-DIM`, `child&PL`), when
    /// the entry is not its own stem.
    pub stem: Option<String>,
}

/// A `.cut` line that is neither blank, a header, a comment, nor an entry.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("malformed MOR lexicon line {line_no}: {line:?}")]
pub struct MorCutParseError {
    /// One-based line number within the file.
    pub line_no: usize,
    /// The offending line, verbatim.
    pub line: String,
}

/// Parse the text of one `.cut` file. Fails closed on the first line that does
/// not fit the entry grammar (a stray git conflict marker included), so a
/// lexicon that breaks the format is reported rather than silently dropping
/// words from the verdicts.
pub fn parse_cut(text: &str) -> Result<Vec<MorEntry>, MorCutParseError> {
    let mut entries = Vec::new();
    for (index, raw) in text.lines().enumerate() {
        let line = strip_comment(raw).trim();
        if line.is_empty() || line.starts_with('@') {
            continue;
        }
        let entry = parse_entry(line).ok_or_else(|| MorCutParseError {
            line_no: index + 1,
            line: raw.to_string(),
        })?;
        entries.push(entry);
    }
    Ok(entries)
}

/// Cut a line at the first `%` that is not inside a quoted stem. Lexicon
/// comments are whole lines or trail an entry (`... "kill" % from "mercenary"`).
fn strip_comment(line: &str) -> &str {
    let mut in_quote = false;
    for (index, ch) in line.char_indices() {
        match ch {
            '"' => in_quote = !in_quote,
            '%' if !in_quote => return &line[..index],
            _ => {}
        }
    }
    line
}

/// Parse `form {[key value][key value]} "stem"`, returning `None` when the
/// line does not fit that shape.
fn parse_entry(line: &str) -> Option<MorEntry> {
    let (form, rest) = line.split_once(char::is_whitespace)?;
    let rest = rest.trim_start();
    let body = rest.strip_prefix('{')?;
    let (attrs, tail) = body.split_once('}')?;
    let mut scat = None;
    let mut dcat = None;
    let mut attaches_to_bare_stem = true;
    let mut remaining = attrs.trim();
    while !remaining.is_empty() {
        let inner = remaining.strip_prefix('[')?;
        let (attr, after) = inner.split_once(']')?;
        let (key, value) = attr.split_once(char::is_whitespace).unwrap_or((attr, ""));
        match key {
            "scat" => scat = Some(value.trim().to_string()),
            "dcat" => dcat = Some(value.trim().to_string()),
            "bare" if value.trim() == "no" => attaches_to_bare_stem = false,
            _ => {}
        }
        remaining = after.trim_start();
    }
    // Three tail shapes occur in the lexicon: nothing, a quoted stem, or an
    // `=gloss=` on a dialect entry (`aa {[scat co][dia sing]} =emphasis=`).
    // A gloss says what the form means, not what it is, so it is read and
    // discarded rather than treated as a stem.
    let tail = tail.trim();
    let stem = if tail.is_empty() {
        None
    } else if let Some(quoted) = tail.strip_prefix('"') {
        Some(quoted.strip_suffix('"')?.to_string())
    } else {
        tail.strip_prefix('=')?.strip_suffix('=')?;
        None
    };
    Some(MorEntry {
        form: form.to_string(),
        scat,
        dcat,
        attaches_to_bare_stem,
        stem,
    })
}

/// The family of a MOR category, the one place the category vocabulary is
/// read. `n:prop` and `n:pt` are nouns for the purpose of "does the lexicon
/// know a noun base here"; whether an entry is the PLAIN noun category is a
/// separate, exact question answered by [`MorEntry::scat`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MorClass {
    /// `co`: a communicator, the interjection class of CHILDES.
    Communicator,
    /// `n` and its subcategories.
    Noun,
    /// `v` and its subcategories (`cop`, `aux` and `mod` are not verbs here).
    Verb,
    /// `adj` and its subcategories.
    Adjective,
    /// `adv` and its subcategories.
    Adverb,
    /// Everything else: pronouns, determiners, prefixes, affix kinds.
    Other,
}

impl MorClass {
    /// The family of a `scat` or one side of a `dcat` value.
    pub fn of(category: &str) -> Self {
        match category.split(':').next().unwrap_or(category) {
            "co" => Self::Communicator,
            "n" => Self::Noun,
            "v" => Self::Verb,
            "adj" => Self::Adjective,
            "adv" => Self::Adverb,
            _ => Self::Other,
        }
    }
}

/// The exact category strings a verdict is derived for. Subcategories
/// (`n:prop`, `n:pt`) are deliberately not these.
const PLAIN_COMMUNICATOR: &str = "co";
const PLAIN_NOUN: &str = "n";

/// Grammatical number of a noun verdict, read from the entry's stem affix.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum NounNumber {
    /// No plural affix on the entry (`doggy "dog-DIM"`, or a bare stem).
    Singular,
    /// The entry carries `&PL` or `-PL` (`children "child&PL"`).
    Plural,
}

/// A noun verdict: the UD lemma and number the lexicon determines for a form.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct NounVerdict {
    /// The lexicon form, lowercase.
    pub form: String,
    /// The lemma `%mor` should carry: the bare stem for a plural entry, the
    /// form itself otherwise (UD keeps `doggy` as its own lemma).
    pub lemma: String,
    /// The number the entry states.
    pub number: NounNumber,
}

/// Where the embedded verdicts came from, so the data file is self-describing.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct VerdictSource {
    /// GitHub repository, `TalkBank/mor`.
    pub repo: String,
    /// The commit the lexicon was read at.
    pub commit: String,
    /// The lexicon directory within the repository.
    pub path: String,
    /// The command that regenerates the file.
    pub generator: String,
}

/// The on-disk shape of `data/eng_lexicon_verdicts.json`: unvalidated.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RawVerdicts {
    /// Provenance of the data.
    pub source: VerdictSource,
    /// Forms licensed only as communicators, sorted.
    pub communicator: Vec<String>,
    /// Forms licensed as communicators AND as something else (`okay`, `well`,
    /// `right`), sorted. These get no category verdict on their own; a rule
    /// with independent evidence that the word is a discourse element may
    /// consult them.
    pub communicator_among_others: Vec<String>,
    /// Forms licensed only as nouns, sorted by form.
    pub noun: Vec<NounVerdict>,
}

/// Why a [`RawVerdicts`] was refused by [`LexiconVerdicts::try_from`].
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum LexiconVerdictsError {
    /// A form is empty, carries whitespace, or is not lowercase.
    #[error("lexicon verdict form is not a lowercase token: {0:?}")]
    MalformedForm(String),
    /// A noun lemma is empty, carries whitespace, or is not lowercase.
    #[error("lexicon verdict lemma is not a lowercase token: {0:?}")]
    MalformedLemma(String),
    /// The same form carries more than one verdict.
    #[error("lexicon verdict form {0:?} appears more than once")]
    Duplicate(String),
}

/// The lexicon's verdict for one surface form.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LexiconVerdict {
    /// Licensed only as a communicator: an interjection with no features.
    Communicator,
    /// Licensed as a communicator among other categories: an interjection
    /// only where something outside the lexicon says so.
    CommunicatorAmongOthers,
    /// Licensed only as a noun, with the lemma and number the entry states.
    Noun(NounVerdict),
}

/// The validated verdicts: every form is a lowercase token and carries exactly
/// one verdict. Constructed only through [`TryFrom<RawVerdicts>`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LexiconVerdicts {
    forms: HashMap<String, LexiconVerdict>,
}

impl LexiconVerdicts {
    /// The verdict for `surface`, looked up case-insensitively. `None` means
    /// the lexicon either does not know the form or licenses it for more
    /// than one category, and the caller must leave Stanza's analysis alone.
    pub fn verdict(&self, surface: &str) -> Option<&LexiconVerdict> {
        // Nearly every lookup arrives already lowercase (the caller skips
        // capitalized words); allocate the lowered key only when needed.
        if surface.chars().any(char::is_uppercase) {
            return self.forms.get(&surface.to_lowercase());
        }
        self.forms.get(surface)
    }

    /// Number of communicator verdicts.
    pub fn communicator_count(&self) -> usize {
        self.forms
            .values()
            .filter(|v| matches!(v, LexiconVerdict::Communicator))
            .count()
    }

    /// Number of noun verdicts.
    pub fn noun_count(&self) -> usize {
        self.forms
            .values()
            .filter(|v| matches!(v, LexiconVerdict::Noun(_)))
            .count()
    }
}

fn is_lowercase_token(s: &str) -> bool {
    !s.is_empty() && !s.chars().any(char::is_whitespace) && s == s.to_lowercase()
}

impl TryFrom<RawVerdicts> for LexiconVerdicts {
    type Error = LexiconVerdictsError;

    fn try_from(raw: RawVerdicts) -> Result<Self, Self::Error> {
        let mut forms = HashMap::with_capacity(raw.communicator.len() + raw.noun.len());
        let mut admit = |form: String, verdict: LexiconVerdict| {
            if !is_lowercase_token(&form) {
                return Err(LexiconVerdictsError::MalformedForm(form));
            }
            if forms.contains_key(&form) {
                return Err(LexiconVerdictsError::Duplicate(form));
            }
            forms.insert(form, verdict);
            Ok(())
        };
        for (forms, verdict) in [
            (raw.communicator, LexiconVerdict::Communicator),
            (
                raw.communicator_among_others,
                LexiconVerdict::CommunicatorAmongOthers,
            ),
        ] {
            for form in forms {
                admit(form, verdict.clone())?;
            }
        }
        for verdict in raw.noun {
            if !is_lowercase_token(&verdict.lemma) {
                return Err(LexiconVerdictsError::MalformedLemma(verdict.lemma));
            }
            admit(verdict.form.clone(), LexiconVerdict::Noun(verdict))?;
        }
        Ok(Self { forms })
    }
}

/// The suffixes with which MOR derives a NON-noun reading from a known base,
/// each with the classes of base it attaches to. Verb inflections come from
/// MOR's `cr.cut`; every other row is an entry of `0affix.cut`: the
/// `[dcat result:base]` rows whose result is not a noun, and the
/// `[scat adjsfx]` rows, which keep an adjective an adjective (comparative
/// `-er`, `-ish`, `-like`) and carry no `dcat`. [`derive_verdicts`] checks
/// the affix entries it is given against this table and fails closed when
/// the lexicon carries a non-noun-producing suffix this table lacks, so an
/// upstream addition cannot silently reopen the defect. Noun-producing
/// suffixes (`-ness`, `-er` agentive, `-ie` diminutive) are absent on
/// purpose: a noun derived from a noun is still a noun.
const NON_NOUN_DERIVATIONS: &[(&str, &[MorClass])] = &[
    // Verb inflection: `lives`, `building`, `feeling`, `pushed`.
    ("s", &[MorClass::Verb]),
    ("es", &[MorClass::Verb]),
    ("ing", &[MorClass::Verb]),
    ("ed", &[MorClass::Verb]),
    // Adjective from a noun, a verb, or an adjective: `sticky`, `doggy`,
    // `childish`, `lawyer's`, `washable`, `bigger`.
    ("y", &[MorClass::Noun, MorClass::Verb, MorClass::Adjective]),
    ("i", &[MorClass::Noun, MorClass::Verb, MorClass::Adjective]),
    ("ly", &[MorClass::Noun, MorClass::Adjective]),
    ("li", &[MorClass::Noun]),
    ("ish", &[MorClass::Noun, MorClass::Adjective]),
    ("less", &[MorClass::Noun]),
    ("like", &[MorClass::Noun, MorClass::Adjective]),
    ("ful", &[MorClass::Noun]),
    ("al", &[MorClass::Noun, MorClass::Adjective]),
    ("-ass", &[MorClass::Noun, MorClass::Adjective]),
    ("istic", &[MorClass::Adjective]),
    ("'s", &[MorClass::Noun]),
    ("'", &[MorClass::Noun]),
    ("able", &[MorClass::Verb]),
    ("ab", &[MorClass::Verb]),
    ("abil", &[MorClass::Verb]),
    ("er", &[MorClass::Adjective]),
    ("est", &[MorClass::Adjective]),
    // Adverb from a noun or an adjective.
    ("wise", &[MorClass::Noun]),
    ("ally", &[MorClass::Adjective]),
    // Verb from a noun or adjective.
    ("ize", &[MorClass::Noun, MorClass::Adjective]),
    ("iz", &[MorClass::Noun, MorClass::Adjective]),
    ("ze", &[MorClass::Noun]),
];

/// A derivational affix in the lexicon that produces a non-noun and is not in
/// [`NON_NOUN_DERIVATIONS`]: the verdicts cannot be trusted until it is.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error(
    "MOR lexicon derives a {result:?} from a {base:?} base with suffix {suffix:?}, which \
     NON_NOUN_DERIVATIONS does not list; add it before regenerating verdicts"
)]
pub struct UncoveredDerivation {
    /// The suffix form as written in `0affix.cut`.
    pub suffix: String,
    /// The class of the `result:` half of its `dcat`, or the affix's own
    /// class for a POS-maintaining suffix.
    pub result: MorClass,
    /// The class of the `:base` half of its `dcat`.
    pub base: MorClass,
}

/// Whether MOR could read `form` as something other than a noun by stripping
/// a productive suffix and finding the base in the lexicon. Spelling variants
/// stand in for MOR's allomorphy rules: a restored final `e` (`liv-ing` from
/// `live`), an undoubled consonant (`runn-ing` from `run`), and `i` back to
/// `y` (`bab-ies` from `baby`).
fn derivable_as_non_noun(form: &str, bases: &HashMap<MorClass, HashSet<String>>) -> bool {
    NON_NOUN_DERIVATIONS.iter().any(|(suffix, classes)| {
        let Some(stripped) = form.strip_suffix(suffix) else {
            return false;
        };
        if stripped.is_empty() {
            return false;
        }
        // Each candidate mirrors one allomorphy rule of MOR's `ar/*.cut`:
        // the bare base; `n-final-e` / `v-ate` (`liv-ing` from `live`);
        // `n-geminates` (`runn-ing` from `run`); `n-cry` / `v-try`
        // (`bab-ies` from `baby`); `v-tie` (`ly-ing` from `lie`).
        let mut candidates = vec![stripped.to_string(), format!("{stripped}e")];
        let chars: Vec<char> = stripped.chars().collect();
        if chars.len() >= 2 && chars[chars.len() - 1] == chars[chars.len() - 2] {
            candidates.push(chars[..chars.len() - 1].iter().collect());
        }
        if let Some(without_i) = stripped.strip_suffix('i') {
            candidates.push(format!("{without_i}y"));
        }
        if let Some(without_y) = stripped.strip_suffix('y') {
            candidates.push(format!("{without_y}ie"));
        }
        classes.iter().any(|class| {
            bases
                .get(class)
                .is_some_and(|known| candidates.iter().any(|c| known.contains(c)))
        })
    })
}

/// Fail closed if the lexicon's affix entries derive a non-noun with a suffix
/// the table does not know. Two kinds of row can: a `[dcat result:base]`
/// derivation whose result is not a noun, and a `[scat adjsfx]` suffix, which
/// keeps an adjective an adjective and carries no `dcat`. Prefix entries and
/// allomorphs that never attach to a bare stem are outside the table's job.
fn check_derivation_table(entries: &[MorEntry]) -> Result<(), UncoveredDerivation> {
    for entry in entries {
        if entry.scat.as_deref() == Some("pfx") || !entry.attaches_to_bare_stem {
            continue;
        }
        let (result, base) = match (entry.dcat.as_deref(), entry.scat.as_deref()) {
            (Some(dcat), _) => {
                let Some((result, base)) = dcat.split_once(':') else {
                    continue;
                };
                (MorClass::of(result), MorClass::of(base))
            }
            (None, Some("adjsfx")) => (MorClass::Adjective, MorClass::Adjective),
            (None, _) => continue,
        };
        if result == MorClass::Noun {
            continue;
        }
        let covered = NON_NOUN_DERIVATIONS
            .iter()
            .any(|(suffix, classes)| *suffix == entry.form && classes.contains(&base));
        if !covered {
            return Err(UncoveredDerivation {
                suffix: entry.form.clone(),
                result,
                base,
            });
        }
    }
    Ok(())
}

/// Derive verdicts from every entry of the lexicon. A form gets a verdict only
/// when every one of its entries licenses the same plain category from the set
/// this module handles, for nouns when every entry agrees on lemma and number
/// and no productive suffix derives a non-noun from a known base. Compound
/// entries (`ice+cream`) are skipped: the CHAT main tier never hands Stanza a
/// `+`-joined form.
pub fn derive_verdicts(
    entries: Vec<MorEntry>,
    source: VerdictSource,
) -> Result<RawVerdicts, UncoveredDerivation> {
    check_derivation_table(&entries)?;

    // Group entries by form and, in the same pass, record every base form
    // MOR could derive from, by the family of its category.
    let mut by_form: HashMap<String, Vec<MorEntry>> = HashMap::new();
    let mut bases: HashMap<MorClass, HashSet<String>> = HashMap::new();
    for entry in entries {
        let Some(scat) = entry.scat.as_deref() else {
            continue;
        };
        if entry.form.contains('+') {
            continue;
        }
        let form = entry.form.to_lowercase();
        bases
            .entry(MorClass::of(scat))
            .or_default()
            .insert(form.clone());
        by_form.entry(form).or_default().push(entry);
    }

    let mut communicator = Vec::new();
    let mut communicator_among_others = Vec::new();
    let mut noun = Vec::new();
    for (form, group) in &by_form {
        if !is_lowercase_token(form) {
            continue;
        }
        if group
            .iter()
            .all(|e| e.scat.as_deref() == Some(PLAIN_COMMUNICATOR))
        {
            communicator.push(form.clone());
            continue;
        }
        if group
            .iter()
            .any(|e| e.scat.as_deref() == Some(PLAIN_COMMUNICATOR))
        {
            communicator_among_others.push(form.clone());
            continue;
        }
        if group.iter().all(|e| e.scat.as_deref() == Some(PLAIN_NOUN)) {
            if derivable_as_non_noun(form, &bases) {
                continue;
            }
            let mut verdicts = group.iter().map(|e| noun_verdict(form, e.stem.as_deref()));
            if let Some(first) = verdicts.next()
                && verdicts.all(|v| v == first)
                && is_lowercase_token(&first.lemma)
            {
                noun.push(first);
            }
        }
    }
    communicator.sort();
    communicator_among_others.sort();
    noun.sort_by(|a, b| a.form.cmp(&b.form));
    Ok(RawVerdicts {
        source,
        communicator,
        communicator_among_others,
        noun,
    })
}

/// Read lemma and number off a noun entry's quoted stem: a plural marker
/// (`child&PL`) makes the stem the lemma; anything else (`dog-DIM`, or no stem)
/// is a singular whose lemma is the form itself.
fn noun_verdict(form: &str, stem: Option<&str>) -> NounVerdict {
    let plural_base = stem
        .filter(|s| s.contains("&PL") || s.contains("-PL"))
        .and_then(|s| s.split(['&', '-']).next())
        .map(|s| s.trim().to_lowercase())
        .filter(|base| !base.is_empty());
    let (lemma, number) = match plural_base {
        Some(base) => (base, NounNumber::Plural),
        None => (form.to_string(), NounNumber::Singular),
    };
    NounVerdict {
        form: form.to_string(),
        lemma,
        number,
    }
}

/// The verdicts embedded from `data/eng_lexicon_verdicts.json`. The file is
/// produced and validated by the generator through the same constructor, so a
/// malformed embed is a build defect, and like every other embedded asset in
/// this crate it panics on first use rather than degrading.
// Data is compile-time-constant: `include_str!` embeds the JSON at build time.
#[allow(clippy::expect_used)]
static EMBEDDED_ENGLISH: LazyLock<LexiconVerdicts> = LazyLock::new(|| {
    let raw: RawVerdicts =
        serde_json::from_str(include_str!("../../data/eng_lexicon_verdicts.json"))
            .expect("embedded eng_lexicon_verdicts.json is well-formed JSON");
    LexiconVerdicts::try_from(raw).expect("embedded eng_lexicon_verdicts.json passes admission")
});

/// The embedded English verdicts.
pub fn embedded_english() -> &'static LexiconVerdicts {
    &EMBEDDED_ENGLISH
}

#[cfg(test)]
mod tests {
    use super::*;

    fn source() -> VerdictSource {
        VerdictSource {
            repo: "TalkBank/mor".into(),
            commit: "test".into(),
            path: "eng/eng/lex".into(),
            generator: "test".into(),
        }
    }

    fn mor_entry(
        form: &str,
        scat: &str,
        dcat: Option<&str>,
        bare: bool,
        stem: Option<&str>,
    ) -> MorEntry {
        MorEntry {
            form: form.into(),
            scat: Some(scat.into()),
            dcat: dcat.map(Into::into),
            attaches_to_bare_stem: bare,
            stem: stem.map(str::to_string),
        }
    }

    fn entry(form: &str, scat: &str, stem: Option<&str>) -> MorEntry {
        mor_entry(form, scat, None, true, stem)
    }

    fn affix(form: &str, scat: &str, dcat: &str, bare: bool) -> MorEntry {
        mor_entry(form, scat, Some(dcat), bare, None)
    }

    #[test]
    fn parse_cut_reads_entries_comments_stems_and_affix_attributes() {
        let text = "@UTF8\n\
                    @Window:\t0_1\n\
                    % a whole-line comment\n\
                    whoops {[scat co]}\n\
                    doggy {[scat n]} \"dog-DIM\"\n\
                    merk {[scat v][dia aael]} \"kill\" % from \"mercenary\"\n\
                    doggy+dog  {[scat n][comp n+n]}\n\
                    aa {[scat co][dia sing]} =emphasis=\n\
                    abil {[dcat adj:v][deriv dv][allo OR v0][block able][bare no]} \"ABLE\"\n";
        let entries = parse_cut(text).unwrap();
        assert_eq!(
            entries,
            vec![
                entry("whoops", "co", None),
                entry("doggy", "n", Some("dog-DIM")),
                entry("merk", "v", Some("kill")),
                entry("doggy+dog", "n", None),
                entry("aa", "co", None),
                MorEntry {
                    form: "abil".into(),
                    scat: None,
                    dcat: Some("adj:v".into()),
                    attaches_to_bare_stem: false,
                    stem: Some("ABLE".into()),
                },
            ]
        );
    }

    #[test]
    fn parse_cut_fails_closed_on_a_malformed_line() {
        let err = parse_cut("ok {[scat n]}\nthis is not an entry\n").unwrap_err();
        assert_eq!(err.line_no, 2);
        assert_eq!(err.line, "this is not an entry");
        let err = parse_cut("ok {[scat n]}\n<<<<<<< HEAD\n").unwrap_err();
        assert_eq!(err.line_no, 2);
    }

    #[test]
    fn mor_class_reads_the_family_of_a_category() {
        assert_eq!(MorClass::of("n:prop"), MorClass::Noun);
        assert_eq!(MorClass::of("v"), MorClass::Verb);
        assert_eq!(MorClass::of("adj:pred"), MorClass::Adjective);
        assert_eq!(MorClass::of("co"), MorClass::Communicator);
        assert_eq!(MorClass::of("pro:dem"), MorClass::Other);
    }

    #[test]
    fn derive_verdicts_requires_every_entry_to_agree_and_nothing_to_derive() {
        let raw = derive_verdicts(
            vec![
                entry("whoops", "co", None),
                // `whoop` is a communicator, a noun and a verb: no verdict.
                entry("whoop", "co", None),
                entry("whoop", "n", None),
                entry("whoop", "v", None),
                // A plural entry carries the bare stem as lemma.
                entry("children", "n", Some("child&PL")),
                // Two noun entries that disagree on number: no verdict.
                entry("fish", "n", None),
                entry("fish", "n", Some("fish&PL")),
                // Compounds never reach Stanza in this shape.
                entry("doggy+dog", "n", None),
                // A proper-noun subcategory is not the plain noun category.
                entry("miffy", "n:prop", None),
                // Noun-only entries MOR could also derive as something else
                // get no verdict: `sticky` is `stick` + adjectival `-y`,
                // `doggy` is `dog` + `-y`, `building` is `build` + `-ing`,
                // `lives` is `live` + `-s`; `babies` derives only from a noun
                // and is kept.
                entry("sticky", "n", None),
                entry("stick", "v", None),
                entry("doggy", "n", Some("dog-DIM")),
                entry("dog", "n", None),
                entry("building", "n", None),
                entry("build", "v", None),
                entry("lives", "n", Some("life&PL")),
                entry("live", "v", None),
                entry("babies", "n", Some("baby&PL")),
                entry("baby", "n", None),
                // `lying` derives from `lie` + `-ing` under MOR's `v-tie`
                // allomorphy: no verdict.
                entry("lying", "n", None),
                entry("lie", "v", None),
                // The affix entries the table must cover.
                affix("y", "adjsfx", "adj:n", true),
                affix("abil", "adjsfx", "adj:v", false),
                affix("pro", "pfx", "adj:n", true),
            ],
            source(),
        )
        .unwrap();
        assert_eq!(raw.communicator, vec!["whoops".to_string()]);
        // `whoop` is a communicator among a noun and a verb.
        assert_eq!(raw.communicator_among_others, vec!["whoop".to_string()]);
        assert_eq!(
            raw.noun,
            vec![
                NounVerdict {
                    form: "babies".into(),
                    lemma: "baby".into(),
                    number: NounNumber::Plural
                },
                NounVerdict {
                    form: "baby".into(),
                    lemma: "baby".into(),
                    number: NounNumber::Singular
                },
                NounVerdict {
                    form: "children".into(),
                    lemma: "child".into(),
                    number: NounNumber::Plural
                },
                NounVerdict {
                    form: "dog".into(),
                    lemma: "dog".into(),
                    number: NounNumber::Singular
                },
            ]
        );
    }

    #[test]
    fn derive_verdicts_fails_closed_on_an_uncovered_non_noun_suffix() {
        let err = derive_verdicts(
            vec![
                entry("dog", "n", None),
                affix("oid", "adjsfx", "adj:n", true),
            ],
            source(),
        )
        .unwrap_err();
        assert_eq!(
            err,
            UncoveredDerivation {
                suffix: "oid".into(),
                result: MorClass::Adjective,
                base: MorClass::Noun,
            }
        );
        // A POS-maintaining adjective suffix carries no `dcat` and is
        // checked by its own class.
        let err = derive_verdicts(
            vec![
                entry("big", "adj", None),
                mor_entry("most", "adjsfx", None, true, None),
            ],
            source(),
        )
        .unwrap_err();
        assert_eq!(err.suffix, "most");
        assert_eq!(
            (err.result, err.base),
            (MorClass::Adjective, MorClass::Adjective)
        );
        // A noun-producing suffix, a prefix, or a non-bare allomorph is not
        // the table's job.
        for harmless in [
            affix("ness", "ndsfx", "n:adj", true),
            affix("pro", "pfx", "adj:n", true),
            affix("oid", "adjsfx", "adj:n", false),
        ] {
            assert!(derive_verdicts(vec![entry("dog", "n", None), harmless], source()).is_ok());
        }
    }

    #[test]
    fn verdicts_constructor_rejects_bad_tokens_and_duplicates() {
        let base = || RawVerdicts {
            source: source(),
            communicator: vec!["whoops".into()],
            communicator_among_others: vec![],
            noun: vec![NounVerdict {
                form: "doggy".into(),
                lemma: "doggy".into(),
                number: NounNumber::Singular,
            }],
        };
        assert!(LexiconVerdicts::try_from(base()).is_ok());

        let mut upper = base();
        upper.communicator = vec!["Whoops".into()];
        assert_eq!(
            LexiconVerdicts::try_from(upper).unwrap_err(),
            LexiconVerdictsError::MalformedForm("Whoops".into())
        );

        let mut spaced = base();
        spaced.noun[0].lemma = "dog gy".into();
        assert_eq!(
            LexiconVerdicts::try_from(spaced).unwrap_err(),
            LexiconVerdictsError::MalformedLemma("dog gy".into())
        );

        let mut across = base();
        across.noun[0].form = "whoops".into();
        assert_eq!(
            LexiconVerdicts::try_from(across).unwrap_err(),
            LexiconVerdictsError::Duplicate("whoops".into())
        );

        let mut within = base();
        within.noun.push(within.noun[0].clone());
        assert_eq!(
            LexiconVerdicts::try_from(within).unwrap_err(),
            LexiconVerdictsError::Duplicate("doggy".into())
        );
    }

    #[test]
    fn verdict_lookup_is_case_insensitive_and_silent_on_unknowns() {
        let verdicts = LexiconVerdicts::try_from(RawVerdicts {
            source: source(),
            communicator: vec!["whoops".into()],
            communicator_among_others: vec![],
            noun: vec![NounVerdict {
                form: "doggy".into(),
                lemma: "doggy".into(),
                number: NounNumber::Singular,
            }],
        })
        .unwrap();
        assert_eq!(
            verdicts.verdict("Whoops"),
            Some(&LexiconVerdict::Communicator)
        );
        assert_eq!(
            verdicts.verdict("whoops"),
            Some(&LexiconVerdict::Communicator)
        );
        assert!(matches!(
            verdicts.verdict("doggy"),
            Some(LexiconVerdict::Noun(_))
        ));
        assert_eq!(verdicts.verdict("well"), None);
        assert_eq!(verdicts.communicator_count(), 1);
        assert_eq!(verdicts.noun_count(), 1);
    }

    /// The shipped data must load, and must carry the facts the rule exists
    /// for. `whoop` is deliberately absent: it is a communicator, a noun and
    /// a verb in the lexicon, so no verdict may be derived for it.
    #[test]
    fn embedded_english_verdicts_load() {
        let verdicts = embedded_english();
        assert!(
            verdicts.communicator_count() > 100,
            "communicator set is implausibly small"
        );
        assert!(
            verdicts.noun_count() > 1000,
            "noun set is implausibly small"
        );
        assert_eq!(
            verdicts.verdict("whoops"),
            Some(&LexiconVerdict::Communicator)
        );
        assert_eq!(
            verdicts.verdict("banana"),
            Some(&LexiconVerdict::Noun(NounVerdict {
                form: "banana".into(),
                lemma: "banana".into(),
                number: NounNumber::Singular,
            }))
        );
        // `doggy` is a noun-only ENTRY, but MOR can also derive it as an
        // adjective (`dog` + `-y`), so no verdict: the lexicon alone cannot
        // settle it. Likewise `sticky` (`stick`), `building` (`build`).
        assert_eq!(verdicts.verdict("doggy"), None);
        assert_eq!(verdicts.verdict("sticky"), None);
        assert_eq!(verdicts.verdict("building"), None);
        // Ambiguous communicators are recorded as such, never as a category.
        assert_eq!(
            verdicts.verdict("okay"),
            Some(&LexiconVerdict::CommunicatorAmongOthers)
        );
        assert_eq!(
            verdicts.verdict("whoop"),
            Some(&LexiconVerdict::CommunicatorAmongOthers)
        );
        assert_eq!(
            verdicts.verdict("well"),
            Some(&LexiconVerdict::CommunicatorAmongOthers)
        );
    }
}
